project:
  type: book
  output-dir: docs

book:
  title: "Key Notes in Plasma Physics"
  author: "Hongyang Zhou"
  repo-url: https://github.com/henry2004y/KeyNotes/
  repo-branch: master
  repo-actions: [edit]
  date: "4/12/2023"
  chapters:
    - index.qmd
    - contents/about.qmd
    - contents/introduction.qmd
    - contents/math.qmd
    - contents/single.qmd
    - contents/fluid.qmd
    - contents/diffres.qmd
    - contents/wave.qmd
    - contents/kinetic.qmd
    - contents/stability.qmd
    - contents/kmhd.qmd
    - contents/gyrokinetics.qmd
    - contents/flr.qmd
    - contents/nonlinear.qmd
    - contents/turbulence.qmd
    - contents/geometry.qmd
    - contents/solarwind.qmd
    - contents/shock.qmd
    - contents/magnetosphere.qmd
    - contents/ionosphere.qmd
    - contents/radiationbelt.qmd
    - contents/aurora.qmd
    - contents/boundary.qmd
    - contents/pic.qmd
    - contents/hybrid.qmd
    - contents/raytracing.qmd
    - contents/test.qmd
    - contents/appendix.qmd
    - contents/references.qmd

bibliography: files/bibliography.bib

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-fold: true
  pdf:
    documentclass: scrreprt
    include-in-header:
      text: |
        \usepackage{cancel}
        \usepackage{centernot}

execute:
  enabled: false
  freeze: true

