[projects]

  [projects.default]
  contents = [
    "about",
    "introduction",
    "math",
    "single",
    "fluid",
    "diffres",
    "wave",
    "kinetic",
    "stability",
    "kmhd",
    "gyrokinetics",
    "flr",
    "nonlinear",
    "turbulence",
    "pic",
    "hybrid",
    "appendix",
    "references",
  ]

  # Full URL, required for the sitemap and robots.txt.
  online_url = "https://henry2004y.github.io/KeyNotes/"
  online_url_prefix = "/KeyNotes"

  # Extra directories to be copied.
  extra_directories = [
    "images",
  ]

  # Port used by serve()
  port = 8004

  output_filename = "keynotes"
