# About {#sec-about}

These are my notes about electromagnetism and plasma physics from multiple courses and textbooks, built via [Quarto](https://quarto.org/) and is made possible by the Julia programming language [@bezanson2017julia] and [pandoc](https://github.com/jgm/pandoc).

Thanks to Prof. F. F. Chen, Y. Y. Lau, Yi Li, Yuming Wang, Richard Fitzpatrick, Paul Bellan, and Gábor Tóth through my journey of learning about plasmas. The backbone of the notes is [@chen2016introduction]. I also learned a lot from Richard Fitzpatrick's online [Plasma Physics Course Notes](https://farside.ph.utexas.edu/teaching/plasma/Plasmahtml). Y. Y. Lau's graduate course notes also have many references to [@bellan2008fundamentals]. [@kilpua2017intro] is a faily short and concise introduction that contains many cute practical notes.

I wish to have separate notes on numerical simulations, but right now these are interwined with the physics here. It is critical to realize that numerical simulations per se do not allow to make fundamental discoveries which go beyond the amount of information that is already contained in the equations one is going to solve on the computer. Therefore, in the first stage, more emphasis should be put on the governing equations as they are the keys to understand the behaviors of plasmas.

赵凯华老师近些年写了本《电浆物理学》，里面的推导非常详细，值得参考。

The future is about nuclear fusion: what do you think?