# Relativity {#sec-relativity}

## Velocity

The path of an object in three-dimensional space (in an inertial frame) may be expressed in terms of three spatial coordinate functions $x^i(t)$ of time $t$, where $i$ is an index which takes values 1, 2, 3.

The three coordinates form the 3d position vector, written as a column vector
$$
\mathbf{x}(t)=
\begin{bmatrix}
x^{1}(t)\\
x^{2}(t)\\
x^{3}(t)
\end{bmatrix}
$$

The components of the velocity $\mathbf{u}$ (tangent to the curve) at any point on the world line are
$$
\mathbf{u}=
\begin{bmatrix}
u^{1}\\
u^{2}\\
u^{3}
\end{bmatrix}
=\frac{\mathrm{d}\mathbf{x}}{\mathrm{d}t}=
\begin{bmatrix}
\frac{\mathrm{d}x^{1}}{\mathrm{d}t} \\
\frac{\mathrm{d}x^{2}}{\mathrm{d}t} \\
\frac{\mathrm{d}x^{3}}{\mathrm{d}t} 
\end{bmatrix}
$$ {#eq-velocity}

Each component is simply written $u^i = \mathrm{d}x^i / \mathrm{d}t$.

## Theory of Relativity

In Einstein's theory of relativity, the path of an object moving relative to a particular frame of reference is defined by four coordinate functions $x_\mu(\tau)$, where $\mu$ is a spacetime index which takes the value 0 for the timelike component, and 1, 2, 3 for the spacelike coordinates. The zeroth component is defined as the time coordinate multiplied by c,
$$
x^0 = ct
$$ {#eq-time-coordinate}

Each function depends on one parameter τ called its _proper time_. As a column vector,
$$
\mathbf{x}=
\begin{bmatrix}
x^{0}(\tau)\\
x^{1}(\tau)\\
x^{2}(\tau)\\
x^{3}(\tau)
\end{bmatrix}
$$

**Time dilation**

From time dilation, the differentials in coordinate time $t$ and proper time $\tau$ are related by
$$
\mathrm{d}t = \gamma(u)\mathrm{d}\tau
$$ {#eq-time-dilation}
where the Lorentz factor,
$$
\gamma(u) = \frac{1}{\sqrt{1 - \frac{u^2}{c^2}}}
$$ {#eq-lorentz-factor}
is a function of the Euclidean norm $u$ of the 3d velocity vector $\mathbf{u}$:
$$
u=\left\|\ {\mathbf{u}}\ \right\|=\sqrt{\left(u^{1}\right)^{2}+\left(u^{2}\right)^{2}+\left(u^{3}\right)^{2}}
$$

### Four-velocity

A _four-velocity_ is a _four-vector_ in four-dimensional spacetime that represents the relativistic counterpart of velocity, which is a three-dimensional vector in space.

Physical events correspond to mathematical points in time and space, the set of all of them together forming a mathematical model of physical four-dimensional spacetime. The history of an object traces a curve in spacetime, called its world line. If the object has mass, so that its speed is necessarily less than the speed of light, the world line may be parametrized by the proper time of the object. The four-velocity is the rate of change of four-position with respect to the proper time along the curve. The velocity, in contrast, is the rate of change of the position in (three-dimensional) space of the object, as seen by an observer, with respect to the observer's time.

The four-velocity is the tangent four-vector of a timelike world line. The four-velocity $\mathbf{U}$ at any point of world line 
$\mathbf{X}(\tau)$ is defined as
$$
\mathbf{U} = \frac{\mathrm{d}\mathbf{X}}{\mathrm{d}\tau}
$$ {#eq-four-velocity}
where $\mathbf{X}$ is the four-position and $\tau$ is the proper time.[^existence]

[^existence]: The four-velocity defined here using the proper time of an object does not exist for world lines for massless objects such as photons travelling at the speed of light.

The relationship between the time $t$ and the coordinate time $x^0$ is defined by
$$
x^0 = ct
$$ {#eq-four-velocity-0}

Taking the derivative of this with respect to the proper time $\tau$, we find the $U_\mu$ velocity component for $\mu = 0$:
$$
U^{0}=\frac{\mathrm{d}x^{0}}{\mathrm{d}\tau}={\frac{\mathrm{d}(ct)}{\mathrm{d}\tau}}=c\frac{\mathrm{d}t}{\mathrm{d}\tau}=c\gamma(u)
$$ {#eq-four-velocity-1}
and for the other 3 components to proper time we get the $U_\mu$ velocity component for $\mu = 1, 2, 3$:
$$
U^{i}=\frac{\mathrm{d}x^{i}}{\mathrm{d}\tau} = \frac{\mathrm{d}x^{i}}{\mathrm{d}t}{\frac{\mathrm{d}t}{\mathrm{d}\tau}} = \frac {\mathrm{d}x^{i}}{\mathrm{d}t} \gamma(u) = \gamma(u)u^{i}
$$ {#eq-four-velocity-3}
where we have used the chain rule from @eq-velocity and @eq-time-dilation.

Thus, we find for the four-velocity $\mathbf{U}$:
$$
\mathbf{U}= \gamma
\begin{bmatrix}
c \\
\mathbf{u}
\end{bmatrix}
$$

Written in standard four-vector notation this is
$$
\mathbf{U}=\gamma \left(c,{\mathbf{u}}\right) = \left(\gamma c,\gamma {\mathbf{u}}\right)
$$ {#eq-four-velocity-vector}
where $\gamma c$ is the temporal component and $\gamma \mathbf{u}$ is the spatial component. Unlike most other four-vectors, the four-velocity has only 3 independent components $u_{x},u_{y},u_{z}$ instead of 4. The $\gamma$ factor is a function of the three-dimensional velocity $\mathbf{u}$.

Using the differential of the four-position in the rest frame, the magnitude of the four-velocity can be obtained by the Minkowski metric with signature (−, +, +, +):
$$
\left\|\mathbf{U} \right\|^{2}=\eta_{\mu\nu}U^{\mu}U^{\nu}=\eta_{\mu\nu}{\frac{\mathrm{d}X^{\mu}}{\mathrm{d}\tau}}{\frac{\mathrm{d}X^{\nu}}{\mathrm{d}\tau}}=-c^{2}
$$ {#eq-four-velocity-mag}
which is always a fixed constant.
