<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Key Notes in Plasma Physics - 17&nbsp; Shock</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../contents/magnetosphere.html" rel="next">
<link href="../contents/solarwind.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../contents/shock.html"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Shock</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Key Notes in Plasma Physics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/henry2004y/KeyNotes/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">About</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/math.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Math</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/single.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Single-Particle Motions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/fluid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Plasmas as Fluid</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/diffres.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Diffusion and Resisvity</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/wave.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Waves</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/kinetic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Kinetic Theory</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/stability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Stability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/kmhd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Kinetic MHD</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/gyrokinetics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Gyrokinetics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/flr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Field Line Resonance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Nonlinear Effects</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/turbulence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Turbulence</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/geometry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Geometry</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/solarwind.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Solar Wind</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/shock.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Shock</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/magnetosphere.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Magnetosphere</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/ionosphere.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Ionosphere</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/radiationbelt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Radiation Belt</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/aurora.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Aurora</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/boundary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Boundary Conditions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/pic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Particle-in-Cell</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/hybrid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Hybrid Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/raytracing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Ray Tracing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-shock-MHD" id="toc-sec-shock-MHD" class="nav-link active" data-scroll-target="#sec-shock-MHD"><span class="header-section-number">17.1</span> MHD Theory</a>
  <ul class="collapse">
  <li><a href="#evolutionarity" id="toc-evolutionarity" class="nav-link" data-scroll-target="#evolutionarity"><span class="header-section-number">17.1.1</span> Evolutionarity</a></li>
  <li><a href="#coplanarity" id="toc-coplanarity" class="nav-link" data-scroll-target="#coplanarity"><span class="header-section-number">17.1.2</span> Coplanarity</a></li>
  <li><a href="#sec-criticality" id="toc-sec-criticality" class="nav-link" data-scroll-target="#sec-criticality"><span class="header-section-number">17.1.3</span> Criticality</a></li>
  <li><a href="#sec-parallel_shock" id="toc-sec-parallel_shock" class="nav-link" data-scroll-target="#sec-parallel_shock"><span class="header-section-number">17.1.4</span> Parallel Shock</a></li>
  <li><a href="#sec-perp_shock" id="toc-sec-perp_shock" class="nav-link" data-scroll-target="#sec-perp_shock"><span class="header-section-number">17.1.5</span> Perpendicular Shock</a></li>
  <li><a href="#oblique-shock" id="toc-oblique-shock" class="nav-link" data-scroll-target="#oblique-shock"><span class="header-section-number">17.1.6</span> Oblique Shock</a></li>
  <li><a href="#sec-switch-shocks" id="toc-sec-switch-shocks" class="nav-link" data-scroll-target="#sec-switch-shocks"><span class="header-section-number">17.1.7</span> Switch-On and Switch-Off Shocks</a></li>
  </ul></li>
  <li><a href="#double-adiabatic-theory" id="toc-double-adiabatic-theory" class="nav-link" data-scroll-target="#double-adiabatic-theory"><span class="header-section-number">17.2</span> Double Adiabatic Theory</a>
  <ul class="collapse">
  <li><a href="#perpendicular-shock" id="toc-perpendicular-shock" class="nav-link" data-scroll-target="#perpendicular-shock"><span class="header-section-number">17.2.1</span> Perpendicular Shock</a></li>
  </ul></li>
  <li><a href="#parallel-shock" id="toc-parallel-shock" class="nav-link" data-scroll-target="#parallel-shock"><span class="header-section-number">17.3</span> Parallel Shock</a>
  <ul class="collapse">
  <li><a href="#turbulent-reformation" id="toc-turbulent-reformation" class="nav-link" data-scroll-target="#turbulent-reformation"><span class="header-section-number">17.3.1</span> Turbulent Reformation</a></li>
  <li><a href="#parallel-shock-particle-reflection" id="toc-parallel-shock-particle-reflection" class="nav-link" data-scroll-target="#parallel-shock-particle-reflection"><span class="header-section-number">17.3.2</span> Parallel Shock Particle Reflection</a></li>
  </ul></li>
  <li><a href="#instabilities-and-waves" id="toc-instabilities-and-waves" class="nav-link" data-scroll-target="#instabilities-and-waves"><span class="header-section-number">17.4</span> Instabilities and Waves</a>
  <ul class="collapse">
  <li><a href="#ion-instabilities-omega-leq-omega_ci" id="toc-ion-instabilities-omega-leq-omega_ci" class="nav-link" data-scroll-target="#ion-instabilities-omega-leq-omega_ci"><span class="header-section-number">17.4.1</span> Ion Instabilities <span class="math inline">\(\omega \leq \omega_{ci}\)</span></a></li>
  <li><a href="#electron-instabilities-and-radiation-omega-sim-omega_pe" id="toc-electron-instabilities-and-radiation-omega-sim-omega_pe" class="nav-link" data-scroll-target="#electron-instabilities-and-radiation-omega-sim-omega_pe"><span class="header-section-number">17.4.2</span> Electron Instabilities and Radiation <span class="math inline">\(\omega \sim \omega_{pe}\)</span></a></li>
  <li><a href="#whistlers" id="toc-whistlers" class="nav-link" data-scroll-target="#whistlers"><span class="header-section-number">17.4.3</span> Whistlers</a></li>
  </ul></li>
  <li><a href="#shock-particle-reflection" id="toc-shock-particle-reflection" class="nav-link" data-scroll-target="#shock-particle-reflection"><span class="header-section-number">17.5</span> Shock Particle Reflection</a>
  <ul class="collapse">
  <li><a href="#specular-reflection" id="toc-specular-reflection" class="nav-link" data-scroll-target="#specular-reflection"><span class="header-section-number">17.5.1</span> Specular Reflection</a></li>
  <li><a href="#consequences-of-shock-reflection" id="toc-consequences-of-shock-reflection" class="nav-link" data-scroll-target="#consequences-of-shock-reflection"><span class="header-section-number">17.5.2</span> Consequences of Shock Reflection</a></li>
  </ul></li>
  <li><a href="#foreshock-transients" id="toc-foreshock-transients" class="nav-link" data-scroll-target="#foreshock-transients"><span class="header-section-number">17.6</span> Foreshock Transients</a>
  <ul class="collapse">
  <li><a href="#hot-flow-anomaly" id="toc-hot-flow-anomaly" class="nav-link" data-scroll-target="#hot-flow-anomaly"><span class="header-section-number">17.6.1</span> Hot Flow Anomaly</a></li>
  <li><a href="#spontaneous-hot-flow-anomaly" id="toc-spontaneous-hot-flow-anomaly" class="nav-link" data-scroll-target="#spontaneous-hot-flow-anomaly"><span class="header-section-number">17.6.2</span> Spontaneous Hot Flow Anomaly</a></li>
  <li><a href="#foreshock-bubble" id="toc-foreshock-bubble" class="nav-link" data-scroll-target="#foreshock-bubble"><span class="header-section-number">17.6.3</span> Foreshock Bubble</a></li>
  <li><a href="#foreshock-cavity" id="toc-foreshock-cavity" class="nav-link" data-scroll-target="#foreshock-cavity"><span class="header-section-number">17.6.4</span> Foreshock Cavity</a></li>
  <li><a href="#foreshock-caviton" id="toc-foreshock-caviton" class="nav-link" data-scroll-target="#foreshock-caviton"><span class="header-section-number">17.6.5</span> Foreshock Caviton</a></li>
  <li><a href="#foreshock-compressional-boundary" id="toc-foreshock-compressional-boundary" class="nav-link" data-scroll-target="#foreshock-compressional-boundary"><span class="header-section-number">17.6.6</span> Foreshock Compressional Boundary</a></li>
  <li><a href="#slams-and-shocklets" id="toc-slams-and-shocklets" class="nav-link" data-scroll-target="#slams-and-shocklets"><span class="header-section-number">17.6.7</span> SLAMS and Shocklets</a></li>
  <li><a href="#density-hole" id="toc-density-hole" class="nav-link" data-scroll-target="#density-hole"><span class="header-section-number">17.6.8</span> Density Hole</a></li>
  </ul></li>
  <li><a href="#subcritical-shocks" id="toc-subcritical-shocks" class="nav-link" data-scroll-target="#subcritical-shocks"><span class="header-section-number">17.7</span> Subcritical Shocks</a></li>
  <li><a href="#location-of-shocks" id="toc-location-of-shocks" class="nav-link" data-scroll-target="#location-of-shocks"><span class="header-section-number">17.8</span> Location of Shocks</a></li>
  <li><a href="#earth-bow-shock" id="toc-earth-bow-shock" class="nav-link" data-scroll-target="#earth-bow-shock"><span class="header-section-number">17.9</span> Earth Bow Shock</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/henry2004y/KeyNotes/edit/master/contents/shock.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-shock" class="quarto-section-identifier"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Shock</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Consider a subsonic disturbance moving through a conventional neutral fluid. As is well-known, sound waves propagating ahead of the disturbance give advance warning of its arrival, and, thereby, allow the response of the fluid to be both smooth and adiabatic. Now, consider a supersonic disturbance. In this case, sound waves are unable to propagate ahead of the disturbance, and so there is no advance warning of its arrival, and, consequently, the fluid response is <em>sharp</em> and <em>non-adiabatic</em>. This type of response is generally known as a <em>shock</em>.</p>
<p>Let us investigate shocks first in MHD fluids. Since information in such fluids is carried via three different waves – namely, <em>fast</em> or <em>compressional-Alfvén waves</em>, <em>intermediate</em> or <em>shear-Alfvén waves</em>, and <em>slow</em> or <em>magnetosonic waves</em> – we might expect MHD fluids to support three different types of shock, corresponding to disturbances traveling faster than each of the aforementioned waves.</p>
<p>In general, a shock propagating through an MHD fluid produces a significant difference in plasma properties on either side of the shock front. The thickness of the front is determined by a balance between convective and dissipative effects. However, dissipative effects in high temperature plasmas are only comparable to convective effects when the spatial gradients in plasma variables become extremely large. Hence, MHD shocks in such plasmas tend to be <em>extremely narrow</em>, and are well-approximated as <em>discontinuities</em> in plasma parameters. The MHD equations, and Maxwell’s equations, can be integrated across a shock to give a set of jump conditions which relate plasma properties on each side of the shock front. If the shock is sufficiently narrow then these relations become independent of its detailed structure. We will derive the jump conditions for a narrow, planar, steady-state, MHD shock in <a href="#sec-shock-MHD"><span>Section&nbsp;17.1</span></a>.</p>
<p>The realization of extreme sharpness of a collisionless shock like the Earth’s bow shock immediately posed a serious problem for the MHD description of collisionless shocks. In collisionless magnetohydrodynamics there is no known dissipation mechanism that could lead to the observed extremely short transition scales <span class="math inline">\(\Delta\sim r_{Li}\)</span> in high Mach number flows which are comparable to the ion gyro-radius <span class="math inline">\(r_{Li}\)</span>. MHD neglects any differences in the properties of electrons and ions and thus barely covers the very physics of shocks on the observed scales. In its frame, shocks are considered as infinitely narrow discontinuities, narrower than the MHD flow scales <span class="math inline">\(L\gg \Delta \gg \lambda_d\)</span>; on the other hand, these discontinuities must physically be much wider than the dissipation scale <span class="math inline">\(\lambda_d\)</span> with all the physics going on inside the shock transition. This implies that the conditions derived from collisionless magnetohydrodynamics just hold far upstream and far downstream of the shock transition, i.e.&nbsp;far outside the region where the shock interactions are going on. In describing shock waves, collisionless MHD must be used in an asymptotic sense, providing the remote boundary conditions on the shock transition. One must look for processes different from MHD in order to arrive at a description of the processes leading to shock formation and shock dynamics and the structure of the shock transition. In fact, viewed from the MHD single-fluid viewpoint, the shock should not be restricted to the steep shock front, it rather includes the entire shock transition region from outside the foreshock across the shock front down to the boundary layer at the surface of the obstacle. And this holds as well even in two-fluid shock theory that distinguishes between the behaviour of electrons and ions in the plasma fluid. The issue of dissipation is partly indicated in <a href="#sec-criticality"><span>Section&nbsp;17.1.3</span></a>.</p>
<p>The basic process of shock formation is the growth of a small disturbance in the plasma by the action of the intrinsic <em>nonlinearity</em> of flow, independent of the cause of the initial disturbance. The latter can be an external driver like a piston or a blast, it can also be an internal instability. Shocks form when nonlinearity causes steeping (or steepening) of the disturbance in space and some process exists which prevents breaking of the steep wave. Such processes are of <em>dissipative</em> or <em>dispersive</em> nature and are discussed in ascending importance.</p>
<p>It is important to emphasize that the various modes of waves are responsible for the generation of anomalous dissipation, shock ramp broadening, generation of turbulence in the shock environment and shock ramp itself, as well as for particle acceleration, shock particle reflection and the successive effects. The idea is that in a plasma that consists of electrodynamically active particles the excitation of the various plasma wave modes in the electromagnetic field as collective effects is the easiest way of energy distribution and transport. There is very little momentum needed in order to accelerate a wave, even though many particles are involved in the excitation and propagation of the wave, much less momentum than accelerating a substantial number of particles to medium energy. Therefore any more profound understanding of shock processes cannot avoid bothering with waves, instabilities, wave excitation and wave-particle interaction.</p>
<p>A general review of collisionless shocks is given by <span class="citation" data-cites="balogh2013physics">Balogh and Treumann (<a href="#ref-balogh2013physics" role="doc-biblioref">2013</a>)</span>.</p>
<section id="sec-shock-MHD" class="level2" data-number="17.1">
<h2 data-number="17.1" class="anchored" data-anchor-id="sec-shock-MHD"><span class="header-section-number">17.1</span> MHD Theory</h2>
<p>The conserved form of MHD equations can be written as: <span id="eq-mhd_conservation"><span class="math display">\[
\begin{aligned}
\nabla\cdot\mathbf{B}=0 \\
\frac{\partial \mathbf{B}}{\partial t} - \nabla\times (\mathbf{V}\times \mathbf{B})=0 \\
\frac{\partial\rho}{\partial t} + \nabla\cdot(\rho\,\mathbf{V})=0 \\
\frac{\partial (\rho\,\mathbf{V})}{\partial t} + \nabla\cdot\mathbf{T}=0 \\
\frac{\partial U}{\partial t} + \nabla\cdot\mathbf{u}=0
\end{aligned}
\tag{17.1}\]</span></span> where <span class="math display">\[
\mathbf{T} = \rho\,\mathbf{V}\,\mathbf{V} + \left(p+ \frac{B^2}{2\mu_0}\right)\mathbf{I}- \frac{\mathbf{B}\mathbf{B}}{\mu_0}
\]</span> is the total (i.e., including electromagnetic, as well as plasma, contributions) stress tensor, <span class="math inline">\(\mathbf{I}\)</span> the identity tensor, <span class="math display">\[
U = \frac{1}{2}\rho V^2 + \frac{p}{\gamma-1} + \frac{B^2}{2\mu_0}
\]</span> the total energy density, and <span class="math display">\[
\mathbf{u} = \left(\frac{1}{2}\rho V^2+ \frac{\gamma}{\gamma -1}p\right)\mathbf{V} + \frac{\mathbf{B}\times (\mathbf{V}\times \mathbf{B})}{\mu_0}
\]</span> the total energy flux density.</p>
<p>Let us move into the rest frame of the shock. For a 1D shock, suppose that the shock front coincides with the <span class="math inline">\(y\)</span>-<span class="math inline">\(z\)</span> plane. Furthermore, let the regions of the plasma upstream and downstream of the shock, which are termed regions 1 and 2, respectively, be <em>spatially uniform</em> and <em>time-static</em>, i.e.&nbsp;<span class="math inline">\(\partial/\partial t = \partial/\partial x = \partial/\partial y = 0\)</span>. Moreover, <span class="math inline">\(\partial/\partial x=0\)</span>, except in the immediate vicinity of the shock. Finally, let the velocity and magnetic fields upstream and downstream of the shock all lie in the <span class="math inline">\(x\)</span>-<span class="math inline">\(y\)</span> plane. The situation under discussion is illustrated in the figure below.</p>
<div id="fig-planar_shock" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="https://farside.ph.utexas.edu/teaching/plasma/lectures/img2110.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;17.1: A planar shock, where the velocity and magnetic fields upstream and downstream of the shock all lie in the <span class="math inline">\(x\)</span>-<span class="math inline">\(y\)</span> plane.</figcaption>
</figure>
</div>
<p>Here, <span class="math inline">\(\rho_1\)</span>, <span class="math inline">\(p_1\)</span>, <span class="math inline">\(\mathbf{V}_1\)</span>, and <span class="math inline">\(\mathbf{B}_1\)</span> are the downstream mass density, pressure, velocity, and magnetic field, respectively, whereas <span class="math inline">\(\rho_2\)</span>, <span class="math inline">\(p_2\)</span>, <span class="math inline">\(\mathbf{V}_2\)</span>, and <span class="math inline">\(\mathbf{B}_2\)</span> are the corresponding upstream quantities.</p>
<p>The basic RH relations are listed in <a href="https://en.wikipedia.org/wiki/Shocks_and_discontinuities_(magnetohydrodynamics)">MHD shocks</a>. In the immediate vicinity of the planar shock, <a href="#eq-mhd_conservation">Equation&nbsp;<span>17.1</span></a> reduce to <span class="math display">\[
\begin{aligned}
\frac{\mathrm{d}B_{x}}{\mathrm{d}x}=0 \\
\frac{\mathrm{d}}{\mathrm{d}x}(V_x\,B_y-V_y\,B_x)=0 \\
\frac{\mathrm{d} (\rho\, V_x)}{\mathrm{d}x}=0 \\
\frac{\mathrm{d} T_{xx}}{\mathrm{d}x}=0 \\
\frac{\mathrm{d} T_{xy}}{\mathrm{d}x}=0 \\
\frac{\mathrm{d} u_x}{\mathrm{d}x}=0
\end{aligned}
\]</span></p>
<p>Integration across the shock yields the desired jump conditions: <span id="eq-RH_planar_sol"><span class="math display">\[
\begin{aligned}
\lfloor B_x\rceil=0 \\
\lfloor V_x\,B_y-V_y\,B_x\rceil=0 \\
\lfloor \rho\,V_x\rceil=0 \\
\lfloor \rho\,V_x^{\,2}+p + B_y^{\,2}/2\mu_0\rceil=0 \\
\lfloor \rho\,V_x\,V_y - B_x\,B_y/\mu_0\rceil=0 \\
\Big\lfloor \frac{1}{2}\,\rho\,V^2\,V_x + \frac{\gamma}{\gamma-1}\,p\,V_x + \frac{B_y\,(V_x\,B_y-V_y\,B_x)}{\mu_0}\Big\rceil=0
\end{aligned}
\tag{17.2}\]</span></span> where <span class="math inline">\(\lfloor A \rceil = A_2 - A_1\)</span> is the difference across the shock. These relations are often called the Rankine-Hugoniot relations for MHD. There are 6 scalar equations and 12 scalar variables all together. Assuming that all of the upstream plasma parameters are known, there are 6 unknown parameters in the problem–namely, <span class="math inline">\(B_{x\,2}\)</span>, <span class="math inline">\(B_{y\,2}\)</span>, <span class="math inline">\(V_{x\,2}\)</span>, <span class="math inline">\(V_{y\,2}\)</span>, <span class="math inline">\(\rho_2\)</span>, and <span class="math inline">\(p_2\)</span>. These 6 unknowns are fully determined by the six jump conditions. If we loose the planar assumption, then we typically write the <span class="math inline">\(x\)</span>-component as the normal component (<span class="math inline">\(v_n, B_n\)</span>) and the combined <span class="math inline">\(y\)</span>- and <span class="math inline">\(z\)</span>-components as the tangential component (<span class="math inline">\(v_t,B_t\)</span>). Luckily this is still deterministic. However, the general case is very complicated!</p>
<p>A clear exposition of the two types of strong discontinuities, namely the shock wave and the tangential discontinuity can be found in §84, Landau &amp; Lifshitz. By definition shocks are transition layers across which there is a transport of particles, whereas discontinuities are transition layers across which there is no particle transport. Thus in shocks <span class="math inline">\(V_n \neq 0\)</span>, and in discontinuities <span class="math inline">\(V_n = 0\)</span>. Take a reference frame fixed to the discontinuity with x-axis along the normal. Since mass, momentum and energy is conserved across the discontinuity, we must have from <a href="#eq-RH_planar_sol">Equation&nbsp;<span>17.2</span></a> for inviscid flows (no magnetic field, y-direction represents the tangential direction), <span class="math display">\[
\begin{aligned}
\lfloor \rho v_x\rceil=0 \\
\lfloor \rho v_x^2 + p \rceil = 0, \lfloor \rho v_x v_y \rceil=0 \\
\lfloor \rho v_x\left(\frac{1}{2}v^2 + h\right)\rceil=0
\end{aligned}
\]</span></p>
<p>In tangential discontinuities, no particle transport means <span class="math inline">\(v_{1x} = v_{2x} = 0\)</span>. Then the x-momentum jump implies <span class="math inline">\(\lfloor p \rceil=0\)</span>, where the y-momentum jump sets no restrictions on <span class="math inline">\(v_y\)</span>. There is also no restriction on <span class="math inline">\(\rho\)</span>. Energy equation is also satisfied. Thus, in tangential discontinuities, the density and tangential velocity components can be discontinuities, whereas the pressure must be continuous and the normal velocity component must be zero.</p>
<p>The categories of the solution of <a href="#eq-RH_planar_sol">Equation&nbsp;<span>17.2</span></a> are shown in <a href="#tbl-shocks-discontinuities">Table&nbsp;<span>17.1</span></a>. The <span class="math inline">\(\pm\)</span> signs denote the changes of the downstream compared with the upstream (<span class="math inline">\(+\)</span> means increase, <span class="math inline">\(-\)</span> means decrease).</p>
<div id="tbl-shocks-discontinuities" class="anchored">
<table class="table">
<caption>Table&nbsp;17.1: Classes of MHD shocks and discontinuities</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 25%">
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 6%">
<col style="width: 17%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Type</th>
<th style="text-align: center;">Particle Transport</th>
<th style="text-align: center;"><span class="math inline">\(\rho\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathbf{v}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(p\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\mathbf{B}\)</span></th>
<th style="text-align: center;">T</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Tangential</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;"><span class="math inline">\(\pm\)</span></td>
<td style="text-align: center;"><span class="math inline">\(V_n=0\)</span></td>
<td style="text-align: center;">continuous</td>
<td style="text-align: center;"><span class="math inline">\(B_n = 0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\pm\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Contact</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;"><span class="math inline">\(\pm\)</span></td>
<td style="text-align: center;">continuous</td>
<td style="text-align: center;">continuous</td>
<td style="text-align: center;">continuous</td>
<td style="text-align: center;"><span class="math inline">\(\pm\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Slow</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">+</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">+</td>
<td style="text-align: center;"><span class="math inline">\(B_t\)</span> -</td>
<td style="text-align: center;">+</td>
</tr>
<tr class="even">
<td style="text-align: center;">Intermediate</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">continuous</td>
<td style="text-align: center;"><span class="math inline">\(\pm\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\pm\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\pm\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\pm\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Rotational</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">continuous</td>
<td style="text-align: center;"><span class="math inline">\(V_n=0\)</span>, <span class="math inline">\(V_t - B_t/\sqrt{\mu_0 \rho}=0\)</span></td>
<td style="text-align: center;">continuous</td>
<td style="text-align: center;"><span class="math inline">\(B_n = 0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\pm\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Fast</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">+</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">+</td>
<td style="text-align: center;"><span class="math inline">\(B_t\)</span> +</td>
<td style="text-align: center;">+</td>
</tr>
</tbody>
</table>
</div>
<ol type="1">
<li><p>The contact discontinuity is a special case of tangential discontinuity in which we assume <span class="math inline">\(\lfloor V_t\rceil = 0\)</span>, i.e., the tangential velocity (and so the velocity) is continuous, but not the density and other thermodynamic variables. Since the tangential discontinuities do not have a propagating aspect with respect to the flow, they move with the fluid.</p></li>
<li><p>The Earth’s magnetopause (<a href="magnetosphere.html#sec-magnetopause"><span>Section&nbsp;18.4.1</span></a>) is generally a tangential discontinuity. When there is no flux rope been generated, the magnetopause can be treated as the surface of pressure balance between magnetic pressure, ram pressure and thermal pressure. However, when reconnection triggers flux rope generation, it may become a rotational discontinuity (TO BE CONFIRMED!).</p></li>
<li><p>Intermediate shocks are incompressive and isentropic. The rotational discontinuity is a special case of the intermediate shock. All thermodynamic quantities are continuous across the shock, but the tangential component of the magnetic field can “rotate”. The condition <span class="math inline">\(\lfloor \mathbf{V}_t - \frac{\mathbf{B}_t}{\sqrt{\mu_0 \rho}}\rceil=0\)</span> is known as the <em>Walen relation</em>. Intermediate shocks in general however, unlike rotational discontinuities, can have a discontinuity in the pressure.</p></li>
<li><p>Slow-mode and fast-mode shocks are compressive and are associated with an increase in entropy. This is the key in identifying the downstream from the upstream in the case of slow/fast shocks.</p></li>
<li><p>The Earth’s bow shock is a fast, supercritical shock. An intuitive interpretation of “supercritical” is that the Mach number is so large such that across the shock in the downstream magnetosheath the plasma bulk speed is still larger than the sound speed.</p></li>
</ol>
<section id="evolutionarity" class="level3" data-number="17.1.1">
<h3 data-number="17.1.1" class="anchored" data-anchor-id="evolutionarity"><span class="header-section-number">17.1.1</span> Evolutionarity</h3>
<p>The hyperbolic nature of the conservation laws allows wave propagation only if it is in accord with causality (???). Causality is a general requirement in nature, meaning in this case that the drop in speed across a shock must be large enough for the normal component of the downstream flow to fall below the corresponding downstream mode velocity. For a fast shock this implies the following ordering of the normal flow and magnetosonic velocities to both sides of the shock: <span class="math display">\[
\begin{aligned}
V_{1n} &gt; c_{1ms}^+ \\
V_{2n} &lt; c_{2ms}^+
\end{aligned}
\]</span> where the numbers 1, 2 refer to upstream and downstream of the fast shock wave.</p>
<p>The first condition is necessary for the shock to be formed at all; it is the second condition which (partially) accounts for the evolutionarity. Otherwise the small fast-mode disturbances excited downstream and moving upward towards the shock would move faster than the flow, they would overcome the shock and steepen it without limit<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. Since this cannot happen for a shock to form, the downstream normal speed must be less than the downstream fast magnetosonic speed. Furthermore, for fast shocks the flow velocity must be greater than the intermediate speed on both sides of the shock, while for slow shocks it must be less than the intermediate speed on both sides. These conditions hold because of the same reason as otherwise the corresponding waves would catch up with the shock front, modify and destroy it and no shock could form.</p>
</section>
<section id="coplanarity" class="level3" data-number="17.1.2">
<h3 data-number="17.1.2" class="anchored" data-anchor-id="coplanarity"><span class="header-section-number">17.1.2</span> Coplanarity</h3>
<p>Knowing that for the shock <span class="math inline">\(v_n\neq 0\)</span> and <span class="math inline">\(\lfloor v_n \rceil \neq 0\)</span>, we can eliminate <span class="math inline">\(\lfloor v_t \rceil\)</span> from the <a href="https://en.wikipedia.org/wiki/Shocks_and_discontinuities_(magnetohydrodynamics)">RH relations</a> and obtain <span class="math display">\[
\lfloor v_n \mathbf{B}_t \rceil = \frac{B_n^2}{\mu_0 (\mathrm{something}) }\lfloor \mathbf{B}_t \rceil
\]</span></p>
<p>Hence the cross product of the left with the right hand side must vanish: <span id="eq-shock_coplanarity"><span class="math display">\[
\begin{aligned}
\lfloor \mathbf{B}_t \rceil \times \lfloor v_n\mathbf{B}_t \rceil = 0 \\
(\mathbf{B}_{t2} - \mathbf{B}_{t1})\times(v_{n2}\mathbf{B}_{t2} - v_{n1}\mathbf{B}_{t1}) = 0 \\
(v_{n1} - v_{n2})(\mathbf{B}_{t1}\times\mathbf{B}_{t2}) = 0 \\
\mathbf{B}_{t1} \parallel \mathbf{B}_{t2}
\end{aligned}
\tag{17.3}\]</span></span></p>
<p>The resulting coplanarity theorem implies that the magnetic field across the shock has a 2-D geometry: upstream and dowstream tangential fields are parallel to each other and coplanar with the shock normal <span class="math inline">\(\hat{n}\)</span>.</p>
<p>Coplanarity does not strictly hold, however. For instance, when the shock is non-stationary, i.e.&nbsp;when its width changes with time or in the direction tangential to the shock, <span class="math inline">\(\partial\mathbf{B}/\partial t\)</span> in Faraday’s law does not vanish, and coplanarity becomes violated.</p>
<p>Also, any upstream low frequency electromagnetic plasma wave that propagates along the upstream magnetic field, possesses a magnetic wave field that is perpendicular to the upstream field. When it encounters the shock, this tangential component will be transformed and amplified across the shock. This naturally introduces an out-of-plane magnetic field component, thereby violating the co-planarity condition. There are also other effects which at a real non-MHD shock violate coplanarity.</p>
</section>
<section id="sec-criticality" class="level3" data-number="17.1.3">
<h3 data-number="17.1.3" class="anchored" data-anchor-id="sec-criticality"><span class="header-section-number">17.1.3</span> Criticality</h3>
<p>In space, shock is a dissipative structure in which the kinetic and magnetic energy of a directed plasma flow is partly transferred to heating of the plasma. The dissipation does not take place, however, by means of particle collisions for a shock in space. Collisionless shocks can be divided into <em>super</em>- and <em>sub-critical</em>, according to their Mach-numbers <span class="math inline">\(M &lt; M_c\)</span> being smaller or <span class="math inline">\(M &gt; M_c\)</span> larger than some critical Mach-number <span class="math inline">\(M_c\)</span>. In aerodynamics, the <a href="https://en.wikipedia.org/wiki/Critical_Mach_number">critical Mach number</a> <span class="math inline">\(M^\ast\)</span> of an aircraft is the <em>lowest</em> Mach number at which the airflow over some point of the aircraft reaches the speed of sound, but does not exceed it. For a resistive shock Marshall [1955] had numerically determined the critical Mach number to <span class="math inline">\(M_c\approx 2.76\)</span>.</p>
<p>Subcritical shocks are capable of generating sufficient dissipation to account for retardation, thermalisation and entropy in the time the flow crosses the shock from upstream to downstream. The relevant processes are based on wave-particle interaction between the shocked plasma and the shock-excited turbulent wave fields.</p>
<p>For supercritical shocks this is, however, not the case. Supercritical shocks must evoke mechanisms different from simple wave-particle interaction for getting rid of the excess energy in the bulk flow that cannot be dissipated by any classical anomalous dissipation. Above the critical Mach number the simplest efficient way of energy dissipation is rejection of the in-flowing excess energy from the shock by reflecting a substantial part of the incoming plasma back upstream.</p>
<p>To show how the critical Mach number of a shock arises from the Rankine-Hugoniot relations we consider the strictly perpendicular case with vanishing upstream pressure <span class="math inline">\(P_1 = 0\)</span>. The explicit jump conditions become very simple in this case: <span class="math display">\[
\begin{aligned}
n_1 v_1 &amp;= n_2 v_2 \\
v_1 B_1 &amp;= v_2 B_2 \\
n_1 v_1^2 + \frac{B_1^2}{2\mu_0 m} &amp;= n_2 v_2^2 + \frac{P_2}{m} + \frac{B_2^2}{2\mu_0 m} \\
\frac{v_1^2}{2} + \frac{B_1^2}{\mu_0 m n_1} &amp;= \frac{v_2^2}{2} + \frac{\gamma}{\gamma - 1}\frac{P_2}{m n_2} + \frac{B_1^2}{\mu_0 m n_1}
\end{aligned}
\]</span> where <span class="math inline">\(B\)</span> is the only existing tangential component of the magnetic field here, and <span class="math inline">\(\gamma = 5/3\)</span> is the adiabatic index (valid for fast = adiabatic transitions across the shock). This is the simplest imaginable case of an MHD shock, and it is easy to solve these equations. <a href="#fig-critical_mach_number_mhd_perp_shock">Figure&nbsp;<span>17.2</span></a> shows the resulting relation between the normalised downstream flow <span class="math inline">\(v_2/v_1\)</span> and downstream sound speed <span class="math inline">\(c_{s2}/v_1 = \sqrt{\gamma P_2/n_2}/ v_1\)</span> as function of upstream Alfvén Mach number <span class="math inline">\(M_A = v_1 \sqrt{\mu_0 m n_1} / B_1\)</span>.</p>
<div id="fig-critical_mach_number_mhd_perp_shock" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="../images/Critical_Mach_Number_Perp_Shock.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;17.2: Dependence of the downstream normalised flow <span class="math inline">\(V_2/V_1\)</span> and sound <span class="math inline">\(c_{s2}\)</span> velocities on the upstream Alfvén Mach number for an ideal MHD perpendicular shock with zero upstream pressure <span class="math inline">\(P_2 = 0\)</span>. The crossing of the two curves defines the critical Mach number which is <span class="math inline">\(M_c = 2.76\)</span>.</figcaption>
</figure>
</div>
<p>The two curves in the figure cross each other at the critical Mach number which in the present case is <span class="math inline">\(M_c = 2.76\)</span> and where the downstream sound speed exceeds the flow speed. Below the critical Mach number the downstream flow is still supersonic (though clearly sub-magnetosonic!). Only above the critical Mach number the downstream flow velocity falls below the downstream sound speed. There is thus a qualitative change in the shock character above it that is not contained in the Rankine-Hugoniot conditions.</p>
<p>The determination of the critical Mach number poses an interesting problem. The finite magnetic field compression ratio sets an upper limit to the rate of resistive dissipation that is possible in an MHD shock. Plasmas possess several dissipative lengths, depending on which dissipative process is considered. Any nonlinear wave that propagates in the plasma should steepen as long, until its transverse scale approaches the longest of these dissipative scales. Then dissipation sets on and limits its amplitude.</p>
<p>Thus, when the wavelength of the fast magnetosonic wave approaches the resistive length, the magnetic field decouples from the wave by resistive dissipation, and the wave speed becomes the sound speed downstream of the shock ramp. The condition for the critical Mach number is then given by <span class="math inline">\(v_{n2} = c_{2s}\)</span>. Similarly, for the slow-mode shock, because of its different dispersive properties, the resistive critical-Mach number is defined by the condition <span class="math inline">\(v_{1n} = c_{1s}\)</span><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Since these quantities depend on wave angle, they have to be solved numerically. Prior studies showed that critical fast-mode Mach number varies between 1 and 3, depending on the upstream plasma parameters and flow angle to the magnetic field. It is usually called <em>first</em> critical Mach number, because there is theoretical evidence in simulations for a second critical Mach number, which comes into play when the shock structure becomes time dependent, whistlers accumulate at the shock front and periodically cause its reformation. The dominant dispersion is then the whistler dispersion. An approximate expression for this second or whistler critical Mach number is <span class="math display">\[
M_{2c} \propto \left( \frac{m_i}{m_e} \right)^{1/2}\cos\theta_{Bn}
\]</span> where the constant of proportionality depends on whether one defines the Mach number with respect to the whistler-phase or group velocities. For the former it is <span class="math inline">\(1/2\)</span>, and for the latter <span class="math inline">\(\sqrt{27/64}\)</span> [Oka+, 2006].</p>
<p>It is clear that it is the smallest critical Mach number that determines the behaviour of the shock. In simple words: <span class="math inline">\(M &gt; 1\)</span> is responsible for the existence of the shock under the condition that an obstacle exists in the flow, which is disturbed in some way such that fast waves can grow, steepen and form shocks. When, in addition, the flow exceeds the next lowest Mach number for a given <span class="math inline">\(\theta_{Bn}\)</span> the shock at this angle will make the transition into a supercritical shock and under additional conditions, which have not yet be ultimately clarified, will start reflecting particles back upstream. If, because of some reason, this would not happen, the flow might have to exceed the next higher critical Mach number until reflection becomes possible. In such a case the shock would become metastable in the region where the Mach number becomes supercritical, will steepen and shrink in width until other effects and – ultimately – reflection of particles can set on.</p>
</section>
<section id="sec-parallel_shock" class="level3" data-number="17.1.4">
<h3 data-number="17.1.4" class="anchored" data-anchor-id="sec-parallel_shock"><span class="header-section-number">17.1.4</span> Parallel Shock</h3>
<p>The first special case is the so-called parallel shock in which both the upstream and downstream plasma flows are parallel to the magnetic field, as well as perpendicular to the shock front. In other words, <span id="eq-parallel_shock"><span class="math display">\[
\begin{aligned}
\mathbf{V}_1 = (V_1,\,0,\,0),\quad\mathbf{V}_2 = (V_2,\,0,\,0) \\
\mathbf{B}_1 = (B_1,\,0,\,0),\quad\mathbf{B}_2 = (B_2,\,0,\,0)
\end{aligned}
\tag{17.4}\]</span></span></p>
<p>Substitution into <a href="#eq-RH_planar_sol">Equation&nbsp;<span>17.2</span></a> yields <span id="eq-parallel_shock_relation"><span class="math display">\[
\begin{aligned}
\frac{B_2}{B_1} &amp;= 1\\
\frac{\rho_2}{\rho_1} &amp;= r \\
\frac{v_2}{v_1} &amp;= r^{-1} \\
\frac{p_2}{p_1} &amp;= R \\
\end{aligned}
\tag{17.5}\]</span></span> with <span id="eq-eq-parallel_shock_coef"><span class="math display">\[
\begin{aligned}
r &amp;= \frac{(\gamma + 1)M_1^2}{2+(\gamma-1)M_1^2} \\
R &amp;= 1 + \gamma M_1^2 (1-r^{-1}) = \frac{(\gamma+1)r - (\gamma-1)}{(\gamma+1) - (\gamma-1)r}
\end{aligned}
\tag{17.6}\]</span></span></p>
<p>Here, <span class="math inline">\(M_1 = v_1/v_{s1}\)</span>, where <span class="math inline">\(v_{s1} = \sqrt(\gamma p_1/\rho_1)\)</span> is the upstream sound speed. Thus, the upstream flow is supersonic if <span class="math inline">\(M_1&gt;1\)</span>, and subsonic if <span class="math inline">\(M_1&lt;1\)</span>. Incidentally, as is clear from the above expressions, a parallel shock is unaffected by the presence of a magnetic field. In fact, this type of shock is identical to that which occurs in neutral fluids, and is, therefore, usually called a <em>hydrodynamic shock</em>.</p>
<p>It is easily seen from <a href="#eq-parallel_shock">Equation&nbsp;<span>17.4</span></a> that there is no shock (i.e., no jump in plasma parameters across the shock front) when the upstream flow is exactly sonic: i.e., when <span class="math inline">\(M_1=1\)</span>. In other words, <span class="math inline">\(r=R=1\)</span> when <span class="math inline">\(M_1=1\)</span>. However, if <span class="math inline">\(M_1\neq 1\)</span> then the upstream and downstream plasma parameters become different (i.e., <span class="math inline">\(r\neq 1\)</span>, <span class="math inline">\(R\neq 1\)</span>) and a true shock develops. In fact, it is easily demonstrated that <span id="eq-parallel_shock_coef_range"><span class="math display">\[
\begin{aligned}
\frac{\gamma-1}{\gamma+1} &amp;\leq r \leq \frac{\gamma+1}{\gamma-1} \\
0&amp;\leq R \leq \infty \\
\frac{\gamma-1}{2\,\gamma}&amp;\leq M_1^2\leq \infty
\end{aligned}
\tag{17.7}\]</span></span></p>
<p>Note that the upper and lower limits in the above inequalities are all attained simultaneously.</p>
<p>The previous discussion seems to imply that a parallel shock can be either compressive (i.e., <span class="math inline">\(r&gt;1\)</span>) or expansive (i.e., <span class="math inline">\(r&lt;1\)</span>). Is there a preferential direction across the shock? In other words, can we tell the upstream and the downstream? Yes, with the additional physics principle of the <em>second law of thermodynamics</em>. This law states that the <em>entropy</em> of a closed system can spontaneously increase, but can never spontaneously decrease. Now, in general, the entropy per particle is different on either side of a hydrodynamic shock front. Accordingly, the second law of thermodynamics mandates that the downstream entropy must <em>exceed</em> the upstream entropy, so as to ensure that the shock generates a net increase, rather than a net decrease, in the overall entropy of the system, as the plasma flows through it.</p>
<p>The (suitably normalized) entropy per particle of an ideal plasma takes the form <span class="math display">\[
S = \ln\left(\frac{p}{\rho^\gamma}\right)
\]</span></p>
<p>Hence, the difference between the upstream and downstream entropies is <span class="math display">\[
\lfloor S\rceil =\ln R - \gamma\,\ln r
\]</span></p>
<p>Now, using <a href="#eq-eq-parallel_shock_coef">Equation&nbsp;<span>17.6</span></a>, <span class="math display">\[
r\frac{\mathrm{d}\lfloor S \rceil}{dr} = \frac{r}{R}\frac{dR}{dr} - \gamma = \frac{\gamma(\gamma^2-1)(r-1)^2}{[(\gamma+1)r - (\gamma-1)][(\gamma+1)-(\gamma-1)r]}
\]</span></p>
<p>Furthermore, it is easily seen from <a href="#eq-parallel_shock_coef_range">Equation&nbsp;<span>17.7</span></a> that <span class="math inline">\(\mathrm{d}\lfloor S \rceil/dr\ge 0\)</span> in all situations of physical interest. However, <span class="math inline">\(\lfloor S \rceil = 0\)</span> when <span class="math inline">\(r=1\)</span>, since, in this case, there is no discontinuity in plasma parameters across the shock front. We conclude that <span class="math inline">\(\lfloor S \rceil&lt;0\)</span> for <span class="math inline">\(r&lt;1\)</span>, and <span class="math inline">\(\lfloor S \rceil&gt;0\)</span> for <span class="math inline">\(r&gt;1\)</span>. It follows that the second law of thermodynamics requires hydrodynamic shocks to be <em>compressive</em>: i.e., <span class="math inline">\(r\equiv\rho_2 / \rho_1&gt;1\)</span>. In other words, the plasma density must always <em>increase</em> when a shock front is crossed in the direction of the relative plasma flow. It turns out that this is a general rule which applies to all three types of MHD shock. In the shock rest frame, the shock is associated with an irreversible (since the entropy suddenly increases) transition from supersonic to subsonic flow.</p>
<p>The upstream Mach number, <span class="math inline">\(M_1\)</span>, is a good measure of shock strength: i.e., if <span class="math inline">\(M_1=1\)</span> then there is no shock, if <span class="math inline">\(M_1-1 \ll 1\)</span> then the shock is weak, and if <span class="math inline">\(M_1\gg 1\)</span> then the shock is strong. We can define an analogous downstream Mach number, <span class="math inline">\(M_2=V_2/(\gamma\,p_2/\rho_2)^{1/2}\)</span>. It is easily demonstrated from the jump conditions that if <span class="math inline">\(M_1&gt;1\)</span> then <span class="math inline">\(M_2 &lt; 1\)</span>. In other words, in the shock rest frame, the shock is associated with an irreversible (since the entropy suddenly increases) transition from supersonic to subsonic flow. Note that <span class="math inline">\(r\equiv \rho_2/\rho_1\rightarrow (\gamma+1)/(\gamma-1)\)</span>, whereas <span class="math inline">\(R\equiv p_2/p_1\rightarrow\infty\)</span>, in the limit <span class="math inline">\(M_1\rightarrow \infty\)</span>. In other words, as the shock strength increases, the compression ratio, <span class="math inline">\(r\)</span>, asymptotes to a finite value, whereas the pressure ratio, <span class="math inline">\(P\)</span>, increases without limit. For a conventional plasma with <span class="math inline">\(\gamma=5/3\)</span>, the limiting value of the compression ratio is 4: i.e., the downstream density can never be more than four times the upstream density. We conclude that, in the strong shock limit, <span class="math inline">\(M_1\gg 1\)</span>, the large jump in the plasma pressure across the shock front must be predominately a consequence of a large jump in the plasma <em>temperature</em>, rather than the plasma <em>density</em>. In fact, the definitions of <span class="math inline">\(r\)</span> and <span class="math inline">\(R\)</span> imply that <span class="math display">\[
\frac{T_2}{T_1}\equiv \frac{R}{r}\rightarrow \frac{2\gamma(\gamma-1)M_1^2}{(\gamma+1)^2}\gg 1
\]</span> as <span class="math inline">\(M_1\rightarrow\infty\)</span>. Thus, a strong parallel, or hydrodynamic, shock is associated with intense plasma heating.</p>
<p>As we have seen, the condition for the existence of a hydrodynamic shock is <span class="math inline">\(M_1&gt;1\)</span>, or <span class="math inline">\(V_1 &gt; V_{S\,1}\)</span>. In other words, in the shock frame, the upstream plasma velocity, <span class="math inline">\(V_1\)</span>, must be supersonic. However, by Galilean invariance, <span class="math inline">\(V_1\)</span> can also be interpreted as the propagation velocity of the shock through an initially stationary plasma. It follows that, in a stationary plasma, a parallel, or hydrodynamic, shock propagates along the magnetic field with a supersonic velocity.</p>
</section>
<section id="sec-perp_shock" class="level3" data-number="17.1.5">
<h3 data-number="17.1.5" class="anchored" data-anchor-id="sec-perp_shock"><span class="header-section-number">17.1.5</span> Perpendicular Shock</h3>
<p>The second special case is the so-called <em>perpendicular shock</em> in which both the upstream and downstream plasma flows are perpendicular to the magnetic field, as well as the shock front. In other words, <span id="eq-perp_shock"><span class="math display">\[
\begin{aligned}
\mathbf{V}_1 = (V_1,\,0,\,0),\quad\mathbf{V}_2 = (V_2,\,0,\,0) \\
\mathbf{B}_1 = (0,\,B_1,\,0),\quad\mathbf{B}_2 = (0,\,B_2,\,0)
\end{aligned}
\tag{17.8}\]</span></span></p>
<p>Substitution into <a href="#eq-RH_planar_sol">Equation&nbsp;<span>17.2</span></a> yields <span id="eq-perp_shock_relation"><span class="math display">\[
\begin{aligned}
\frac{B_2}{B_1} &amp;= r\\
\frac{\rho_2}{\rho_1} &amp;= r \\
\frac{v_2}{v_1} &amp;= r^{-1} \\
\frac{p_2}{p_1} &amp;= R \\
\end{aligned}
\tag{17.9}\]</span></span> where <span id="eq-perp_shock_coef"><span class="math display">\[
R = 1+ \gamma\,M_1^{\,2}\,(1-r^{-1}) + \beta_1^{-1}\,(1-r^2)
\tag{17.10}\]</span></span> and <span class="math inline">\(r\)</span> is a real positive root of the quadratic <span id="eq-perp_shock_coef_f"><span class="math display">\[
F(r) = 2\,(2-\gamma)\,r^2+ \gamma\,[2\,(1+\beta_1)+ (\gamma-1)\beta_1 M_a^2]r - \gamma\,(\gamma+1)\,\beta_1\,M_1^2=0
\tag{17.11}\]</span></span></p>
<p>Here, <span class="math inline">\(\beta_a = 2\mu_0 p_1/B_1^2\)</span>.</p>
<p>Now, if <span class="math inline">\(r_1\)</span> and <span class="math inline">\(r_2\)</span> are the two roots of <a href="#eq-perp_shock_coef_f">Equation&nbsp;<span>17.11</span></a> then <span class="math display">\[
r_1 r_2 = -\frac{\gamma(\gamma+1)\beta_1 M_1^2}{2(2-\gamma)}
\]</span></p>
<p>Assuming that <span class="math inline">\(\gamma &lt; 2\)</span>, we conclude that one of the roots is negative, and, hence, that <a href="#eq-perp_shock_coef_f">Equation&nbsp;<span>17.11</span></a> only possesses one physical solution: i.e., there is only one type of MHD shock which is consistent with <a href="#eq-perp_shock">Equation&nbsp;<span>17.8</span></a>. Now, it is easily demonstrated that <span class="math inline">\(F(0)&lt;0\)</span> and <span class="math inline">\(F(\gamma+1/\gamma-1)&gt;0\)</span>. Hence, the physical root lies between <span class="math inline">\(r=0\)</span> and <span class="math inline">\(r=(\gamma+1)/(\gamma-1)\)</span>.</p>
<p>Using similar analysis to that employed in the previous subsection, it is easily demonstrated that the second law of thermodynamics requires a perpendicular shock to be compressive: i.e., <span class="math inline">\(r&gt;1\)</span>. It follows that a physical solution is only obtained when <span class="math inline">\(F(1)&lt;0\)</span>, which reduces to <span class="math display">\[
M_1^{\,2} &gt; 1 + \frac{2}{\gamma\,\beta_1}
\]</span></p>
<p>This condition can also be written <span class="math display">\[
\mathbf{v}_1^2 &gt; \mathbf{v}_{s1}^2 + \mathbf{v}_{A1}^2
\]</span> where <span class="math inline">\(v_{A1} = B_1/\sqrt(\mu_0 \rho_1)\)</span> is the upstream Alfvén speed. <span class="math inline">\(v_{+\,1} = (v_{S\,1}^{\,2} + v_{A\,1}^{\,2})^{1/2}\)</span> can be recognized as the velocity of a fast wave propagating perpendicular to the magnetic field (<a href="wave.html#sec-fast_slow"><span>Section&nbsp;7.7.4</span></a>). Thus, the condition for the existence of a perpendicular shock is that the relative upstream plasma velocity must be <em>greater</em> than the upstream fast wave velocity. Incidentally, it is easily demonstrated that if this is the case then the downstream plasma velocity is less than the downstream fast wave velocity. We can also deduce that, in a stationary plasma, a perpendicular shock propagates across the magnetic field with a velocity which exceeds the fast wave velocity.</p>
<p>In the strong shock limit, <span class="math inline">\(M_1\gg 1\)</span>, <a href="#eq-perp_shock_coef">Equation&nbsp;<span>17.10</span></a> and <a href="#eq-perp_shock_coef_f">Equation&nbsp;<span>17.11</span></a> become identical to <a href="#eq-eq-parallel_shock_coef">Equation&nbsp;<span>17.6</span></a>. Hence, a strong perpendicular shock is very similar to a strong hydrodynamic shock (except that the former shock propagates perpendicular, whereas the latter shock propagates parallel, to the magnetic field). In particular, just like a hydrodynamic shock, a perpendicular shock cannot compress the density by more than a factor <span class="math inline">\((\gamma+1)/(\gamma-1)\)</span>. However, according to <a href="#eq-perp_shock_relation">Equation&nbsp;<span>17.9</span></a>, a perpendicular shock compresses the magnetic field by the same factor that it compresses the plasma density. It follows that there is also an upper limit to the factor by which a perpendicular shock can compress the magnetic field.</p>
</section>
<section id="oblique-shock" class="level3" data-number="17.1.6">
<h3 data-number="17.1.6" class="anchored" data-anchor-id="oblique-shock"><span class="header-section-number">17.1.6</span> Oblique Shock</h3>
<p>Let us now consider the general case in which the plasma velocities and the magnetic fields on each side of the shock are neither parallel nor perpendicular to the shock front. It is convenient to transform into the so-called <em>de Hoffmann-Teller frame</em> in which <span class="math inline">\(|\mathbf{v}_1\times \mathbf{B}_1|=0\)</span>, or <span id="eq-HT_frame_up"><span class="math display">\[
v_{x1}B_{y1} - v_{y1}B_{x1} = 0
\tag{17.12}\]</span></span></p>
<p>In other words, it is convenient to transform to a frame which moves at the local <span class="math inline">\(\mathbf{E}\times\mathbf{B}\)</span> velocity of the plasma.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> It immediately follows from the jump condition of the magnetic convection equation that</p>
<p><span id="eq-HT_frame_down"><span class="math display">\[
v_{x2}B_{y2} - v_{y2}B_{x2} = 0
\tag{17.13}\]</span></span> or <span class="math inline">\(|\mathbf{v}_2\times \mathbf{B}_2|=0\)</span>. Thus, in the de Hoffmann-Teller frame, the upstream plasma flow is parallel to the upstream magnetic field, and the downstream plasma flow is also parallel to the downstream magnetic field. Furthermore, the magnetic contribution to the jump condition <a href="#eq-RH_planar_sol">Equation&nbsp;<span>17.2</span></a> (last eq.) becomes identically zero, which is a considerable simplification.</p>
<p><a href="#eq-HT_frame_up">Equation&nbsp;<span>17.12</span></a> and <a href="#eq-HT_frame_down">Equation&nbsp;<span>17.13</span></a> can be combined with the general jump conditions <a href="#eq-RH_planar_sol">Equation&nbsp;<span>17.2</span></a> to give <span id="eq-oblique_shock_relation"><span class="math display">\[
\begin{aligned}
\frac{\rho_2}{\rho_1}&amp;=r \\
\frac{B_{x\,2}}{B_{x\,1}} &amp;= 1 \\
\frac{B_{y\,2}}{B_{y\,1}} &amp;= r\left(\frac{v_{1}^{\,2} - \cos^2\theta_1\,v_{A\,1}^{\,2}}{v_{1}^{\,2}-r\,\cos^2\theta_1\,v_{A\,1}^{\,2}}\right) \\
\frac{v_{x\,2}}{v_{x\,1}} &amp;= \frac{1}{r} \\
\frac{v_{y\,2}}{v_{y\,1}} &amp;= \frac{v_{1}^{\,2} -\cos^2\theta_1\, v_{A\,1}^{\,2}}{v_{1}^{\,2}-r\,\cos^2\theta_1\,v_{A\,1}^{\,2}} \\
\frac{p_2}{p_1} &amp;= 1+\frac{\gamma v_1^2(r-1)}{v_{s1}^2 r}\left[1-\frac{r v_{A1}^2 [(r+1)v_1^2 - 2r v_{A1}^2\cos^2\theta_1]}{2(v_1^2 -r v_{A1}^2\cos^2\theta_1)^2} \right]
\end{aligned}
\tag{17.14}\]</span></span> where <span class="math inline">\(v_1 = v_{x1}=v_1\cos\theta_1\)</span> is the component of the upstream velocity normal to the shock front, and <span class="math inline">\(\theta_1\)</span> is the angle subtended between the upstream plasma flow and the shock front normal. Finally, given the compression ratio, <span class="math inline">\(r\)</span>, the square of the normal upstream velocity, <span class="math inline">\(v_1^{\,2}\)</span>, is a real root of a cubic equation known as the <em>shock adiabatic</em>: <span id="eq-shock_adiabatic"><span class="math display">\[
\begin{aligned}
0 = &amp; (v_1^2 - r\cos^2\theta_1 v_{A1}^2)^2\{ [(\gamma+1) - (\gamma-1)r]v_1^2 - 2r v_{s1}^2 \} \\
&amp; r\sin^2\theta_1 v_1^2 v_{A1}^2 \{ [\gamma+(2-\gamma)r]v_1^2 - [(\gamma+1) - (\gamma-1)r]r\cos^2\theta_1 v_{A1}^2 \}
\end{aligned}
\tag{17.15}\]</span></span></p>
<p>As before, the second law of thermodynamics mandates that <span class="math inline">\(r&gt;1\)</span>.</p>
<p><strong>Weak shock limit</strong></p>
<p>Let us first consider the weak shock limit <span class="math inline">\(r\rightarrow 1\)</span>. In this case, it is easily seen that the three roots of the shock adiabatic reduce to the slow, intermediate (or Shear-Alfvén), and fast waves, respectively, propagating in the normal direction to the shock front: <span class="math display">\[
\begin{aligned}
v_1^{\,2}&amp;=v_{-\,1}^{\,2}\equiv \frac{v_{A\,1}^{\,2}+v_{S\,1}^{\,2}- [(v_{A\,1}+v_{S\,1})^2 -4\,\cos^2\theta_1\,v_{S\,1}^{\,2}\,v_{A\,1}^{\,2}]^{1/2}}{2} \\
v_1^{\,2}&amp;=\cos^2\theta_1\,v_{A\,1}^{\,2} \\
v_1^{\,2}&amp;=v_{+\,1}^{\,2}\equiv \frac{v_{A\,1}^{\,2}+v_{S\,1}^{\,2} + [(v_{A\,1}+v_{S\,1})^2 -4\,\cos^2\theta_1\,v_{S\,1}^{\,2}\,v_{A\,1}^{\,2}]^{1/2}}{2}
\end{aligned}
\]</span></p>
<p>We conclude that slow, intermediate, and fast MHD shocks degenerate into the associated MHD waves in the limit of small shock amplitude. Conversely, we can think of the various MHD shocks as <em>nonlinear</em> versions of the associated MHD waves. It is easily demonstrated that <span class="math display">\[
v_{+1} &gt; \cos\theta_1 v_{A1} &gt; v_{-1}
\]</span></p>
<p>In other words, a fast wave travels faster than an intermediate wave, which travels faster than a slow wave. It is reasonable to suppose that the same is true of the associated MHD shocks, at least at relatively low shock strength. It follows from <a href="#eq-oblique_shock_relation">Equation&nbsp;<span>17.14</span></a> that <span class="math inline">\(B_{y2}&gt;B_{y1}\)</span> for a fast shock, whereas <span class="math inline">\(B_{y\,2}&lt;B_{y\,1}\)</span> for a slow shock. For the case of an intermediate shock, we can show, after a little algebra, that <span class="math inline">\(B_{y\,2}\rightarrow -B_{y\,1}\)</span> in the limit <span class="math inline">\(r\rightarrow 1\)</span>. We can conclude that (in the de Hoffmann-Teller frame) fast shocks refract the magnetic field and plasma flow (recall that they are parallel in our adopted frame of the reference) <em>away</em> from the normal to the shock front, whereas slow shocks refract these quantities <em>toward</em> the normal. Moreover, the tangential magnetic field and plasma flow generally <em>reverse</em> across an intermediate shock front. This is illustrated in <a href="#fig-mhd_shock_rest_frame">Figure&nbsp;<span>17.3</span></a>.</p>
<div id="fig-mhd_shock_rest_frame" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="https://farside.ph.utexas.edu/teaching/plasma/lectures/img2229.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;17.3: Characteristic plasma flow patterns across the three different types of MHD shock in the shock rest frame.</figcaption>
</figure>
</div>
<p>When <span class="math inline">\(r\)</span> is slightly larger than unity it is easily demonstrated that the conditions for the existence of a slow, intermediate, and fast shock are <span class="math inline">\(v_1&gt; V_{-\,1}\)</span>, <span class="math inline">\(v_1&gt; \cos\theta_1\,V_{A\,1}\)</span>, and <span class="math inline">\(v_1&gt; V_{+\,1}\)</span>, respectively.</p>
<p><strong>Strong shock limit</strong></p>
<p>Let us now consider the strong shock limit, <span class="math inline">\(v_1^{\,2}\gg 1\)</span>. In this case, the shock adiabatic yields <span class="math inline">\(r\rightarrow r_m=(\gamma+1)/(\gamma-1)\)</span>, and <span class="math display">\[
v_1^{\,2} \simeq \frac{r_m}{\gamma-1}\,\frac{2v_{S1}\sin^2\theta_1\,[\gamma + (2-\gamma)\,r_m]\,v_{A1}^2}{r_m-r}
\]</span></p>
<p>There are no other real roots. The above root is clearly a type of fast shock. The fact that there is only one real root suggests that there exists a critical shock strength above which the slow and intermediate shock solutions cease to exist. (In fact, they merge and annihilate one another.) In other words, there is a limit to the strength of a slow or an intermediate shock. On the other hand, there is no limit to the strength of a fast shock. Note, however, that the plasma density and tangential magnetic field cannot be compressed by more than a factor <span class="math inline">\((\gamma+1)/(\gamma-1)\)</span> by any type of MHD shock.</p>
<p><strong><span class="math inline">\(\theta_1=0\)</span></strong></p>
<p>Consider the special case <span class="math inline">\(\theta_1=0\)</span> in which both the plasma flow and the magnetic field are normal to the shock front. In this case, the three roots of the shock adiabatic are <span class="math display">\[
\begin{aligned}
v_1^2&amp;=\frac{2r\,v_{S1}^2}{(\gamma+1)-(\gamma-1)\,r} \\
v_1^2&amp;=r\,v_{A1}^2 \\
v_1^2&amp;=r\,v_{A1}^2
\end{aligned}
\]</span></p>
<p>We recognize the first of these roots as the hydrodynamic shock discussed in <a href="#sec-parallel_shock"><span>Section&nbsp;17.1.4</span></a>. This shock is classified as a slow shock when <span class="math inline">\(V_{S\,1}&lt;v_{A\,1}\)</span>, and as a fast shock when <span class="math inline">\(V_{S\,1}&gt; v_{A\,1}\)</span>. The other two roots are identical, and correspond to shocks which propagate at the velocity <span class="math inline">\(v_1 =\sqrt{r}\, v_{A\,1}\)</span> and “switch-on” the tangential components of the plasma flow and the magnetic field: it can be seen from <a href="#eq-oblique_shock_relation">Equation&nbsp;<span>17.14</span></a> that <span class="math inline">\(v_{y\,1}=B_{y\,1} =0\)</span> whilst <span class="math inline">\(v_{y\,2}\neq 0\)</span> and <span class="math inline">\(B_{y\,2}\neq 0\)</span> for these types of shock.</p>
<p>There we have “switch-on” and “switch-off” shocks which refer to the generation and elimination of tangential components of the plasma flow and the magnetic field. Incidentally, it is also possible to have a “switch-off” shock which eliminates the tangential components of the plasma flow and the magnetic field. According to <a href="#eq-oblique_shock_relation">Equation&nbsp;<span>17.14</span></a>, such a shock propagates at the velocity <span class="math inline">\(v_1=\cos\theta_1\,v_{A\,1}\)</span><a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>. Switch-on and switch-off shocks are illustrated in <a href="#fig-shock_switch_on_off">Figure&nbsp;<span>17.4</span></a>.</p>
<div id="fig-shock_switch_on_off" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="https://farside.ph.utexas.edu/teaching/plasma/lectures/img2247.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;17.4: Characteristic plasma flow patterns across switch-on and switch-off shocks in the shock rest frame.</figcaption>
</figure>
</div>
<p><strong><span class="math inline">\(\theta_1=\pi/2\)</span></strong></p>
<p>Consider another special case <span class="math inline">\(\theta_1=\pi/2\)</span>. As is easily demonstrated, the three roots of the shock adiabatic are <span class="math display">\[
\begin{aligned}
v_1^{\,2}&amp;=r \left(\frac{2v_{S1}^2 + [\gamma+(2-\gamma)\,r]\,v_{A1}^2} {(\gamma+1)-(\gamma-1)\,r}\right)\\
v_1^{\,2}&amp;=0 \\
v_1^{\,2}&amp;=0
\end{aligned}
\]</span></p>
<p>The first of these roots is clearly a fast shock, and is identical to the perpendicular shock discussed in <a href="#sec-perp_shock"><span>Section&nbsp;17.1.5</span></a>, except that there is no plasma flow across the shock front in this case. (IS IT BECAUSE OF THE HT FRAME?) The fact that the two other roots are zero indicates that, like the corresponding MHD waves, slow and intermediate MHD shocks do not propagate perpendicular to the magnetic field.</p>
<p>MHD shocks have been observed in a large variety of situations. For instance, shocks are known to be formed by supernova explosions, by strong stellar winds, by solar flares, and by the solar wind upstream of planetary magnetospheres.</p>
</section>
<section id="sec-switch-shocks" class="level3" data-number="17.1.7">
<h3 data-number="17.1.7" class="anchored" data-anchor-id="sec-switch-shocks"><span class="header-section-number">17.1.7</span> Switch-On and Switch-Off Shocks</h3>
<p>Parallel shocks in MHD should, theoretically, behave exactly like gasdynamic shocks, not having any upstream tangential magnetic field component and should also not have any downstream tangential field. This conclusion does not hold rigourously, however, since plasmas consist of charged particles which are sensitive to fluctuations in the field and can excite various waves in the plasma via electric currents which then become the sources of magnetic fields. The kinetic effects in parallel and quasi-parallel shocks play an important role in their physics and are well capable of generating tangential fields at least on scales shorter than the ion scale.</p>
<p>However, even in MHD as we have seen in the previous subsection, one stumbles across the interesting fact that this kind of shocks must have peculiar properties. The reason is that they are not, as in gasdynamics, the result of steepened <em>sound waves</em>, in which case they would simply be purely electrostatic shocks. At the contrary, the waves propagating parallel to the magnetic field are Alfvén and magnetosonic waves. Alfvén waves contain transverse magnetic field components. These transverse wave fields, in a parallel shock, are in fact tangential to the shock. Hence, if a purely parallel shock steepens, the transverse Alfvén waves do steepen as well, and the shock after the transition from upstream to downstream switches on a tangential magnetic component which originally was not present. Such shocks are called <em>switch-on</em> shocks. Similarly one can imagine the case that a tangential component behind the shock is by the same process switched off by an oppositely directed switch-on field, yielding a <em>switch-off</em> shock.</p>
<p>The problem of whether or not such shocks exist in MHD is related to the question whether or not an Alfvén wave steepens nonlinearly when propagating into a shock. To first order this steepening for an ordinary Alfvén wave is zero. However, to second order a wave trailing the leading Alfvén wave feels its weak transverse magnetic component. This trailing wave therefore propagates slightly oblique to the main magnetic field and thus causes a second order density compression which in addition to generating a shock-like plasma compression changes the Alfvén velocity locally. In the case when the trailing wave is polarised in the same direction as the leading wave it also increases the transverse magnetic field component downstream of the compression thereby to second order switching on a tangential magnetic component. A whole train of trailing waves of same polarisation will thus cause strong steepening in both the density and tangential magnetic field.</p>
<p>Clearly, this kind of shocks is a more or less exotic case of MHD shocks whose importance is not precisely known, with very rare cases of observation.</p>
</section>
</section>
<section id="double-adiabatic-theory" class="level2" data-number="17.2">
<h2 data-number="17.2" class="anchored" data-anchor-id="double-adiabatic-theory"><span class="header-section-number">17.2</span> Double Adiabatic Theory</h2>
<p>The classical approach by Chew, Goldberger, and Low <span class="citation" data-cites="cgl1956">(<a href="#ref-cgl1956" role="doc-biblioref">Chew, Goldberger, and Low 1956</a>)</span> utilizes the MHD framework by assuming isotropic distributions parallel and perpendicular to the magnetic field, which results in scalar pressures on the two sides of the shock. This is now known as the CGL theory.</p>
<p>When we shift to the MHD with anisotropic pressure tensor <span class="math display">\[
P_{ij} = p_\perp \delta_{ij} + (p_\parallel - p_\perp)B_i B_j / B^2
\]</span> where <span class="math inline">\(p_\perp\)</span> and <span class="math inline">\(p_\parallel\)</span> are the pressures perpendicular and parallel w.r.t. the magnetic field, respectively. For the strong magnetic field approximation, the two pressures are related to the plasma density and the magnetic field strength by two adiabatic equations, <span class="math display">\[
\begin{aligned}
\frac{\mathrm{d}}{\mathrm{d}t}\Big( \frac{p_\parallel B^2}{\rho^3} \Big) &amp;= 0 \\
\frac{\mathrm{d}}{\mathrm{d}t}\Big( \frac{p_\perp}{\rho B} \Big) &amp;= 0
\end{aligned}
\]</span></p>
<p>This is also known as the double adiabatic theory, which is also what many people remember to be the key conclusion from the CGL theory. (These are constants at a fixed location in time: it is <em>not</em> correct to apply these across the shock!) Here I want to emphasize the meaning of <em>adiabatic</em> again: this assumes zero heat flux. If the system is not adiabatic, the conservation of these two quantities related to the parallel and perpendicular pressure is no longer valid, and additional terms may come into play such as the stochastic heating.</p>
<p>The general jump conditions for discontinuities in a collisionless anisotropic magnetoplasma in the CGL approximation were derived by <span class="citation" data-cites="abraham1967shock">(<a href="#ref-abraham1967shock" role="doc-biblioref">Abraham-Shrauner 1967</a>)</span>.</p>
<p>The general jump conditions for an anisotropic plasma are given by <span class="citation" data-cites="hudson1970discontinuities">(<a href="#ref-hudson1970discontinuities" role="doc-biblioref">Hudson 1970</a>)</span> <span class="math display">\[
\begin{aligned}
\lfloor \rho v_n \rceil &amp;= 0 \\
\lfloor v_n\mathbf{B}_t - \mathbf{v}_t B_n \rceil &amp;= 0 \\
\lfloor p_\perp + (p_\parallel - p_\perp)\frac{B_n^2}{B^2} + \frac{B_t^2}{8\pi} + \rho v_n^2 \rceil &amp;= 0 \\
\lfloor \frac{B_n \mathbf{B}_t}{4\pi}\Big( \frac{4\pi(p_\parallel - p_\perp)}{B^2} - 1 \Big) +\rho v_n \mathbf{v}_t \rceil &amp;= 0 \\
\lfloor \rho v_n\Big( \frac{\epsilon}{\rho} + \frac{v^2}{2} + \frac{p_\perp}{\rho} + \frac{B_t^2}{4\pi \rho} \Big) + \frac{B_n^2 v_n}{B^2}&amp;(p_\parallel - p_\perp) \\
- \frac{\mathbf{B}_t\cdot\mathbf{v}_t B_n}{4\pi}\Big( 1 - \frac{4\pi(p_\parallel - p_\perp)}{B^2} \Big) \rceil &amp;= 0 \\
\lfloor B_n \rceil &amp;= 0
\end{aligned}
\]</span> where <span class="math inline">\(\rho\)</span> is the mass density, <span class="math inline">\(v\)</span> and <span class="math inline">\(B\)</span> are the velocity and magnetic field strength. Subscripts <span class="math inline">\(t\)</span> and <span class="math inline">\(n\)</span> indicate tangential and normal components with respect to the discontinuity. (THIS IS IN CGS UNITS!) Quantities <span class="math inline">\(p_\perp\)</span> and <span class="math inline">\(p_\parallel\)</span> are the elements of the plasma pressure tensor perpendicular and parallel with respect to the magnetic field. Quantity <span class="math inline">\(\epsilon\)</span> is the internal energy, <span class="math inline">\(\epsilon = p_\perp + p_\parallel/2\)</span>, and <span class="math inline">\(\lfloor Q \rceil = Q_2 - Q_1\)</span>, where subscripts 1 and 2 signify the quantity upstream and downstream of the discontinuity. These equations refer to the conservation of physical quantities, i.e.&nbsp;the mass flux, the tangential component of the electric field, the normal and tangential components of the momentum flux, the energy flux, and, finally, the normal component of the magnetic field. To solve the jump equations for anisotropic plasma conditions upstream and downstream of the shock, one has to use an additional equation, since the set of equations is underdetermined. One common choice is the magnetic field/density jump ratio.</p>
<p>The following derivations follow <span class="citation" data-cites="erkaev2000solution">(<a href="#ref-erkaev2000solution" role="doc-biblioref">Erkaev, Vogl, and Biernat 2000</a>)</span>. Let us introduce two dimensionless parameters, <span class="math inline">\(A_s\)</span> and <span class="math inline">\(A_m\)</span>, which are determined for upstream conditions as <span class="math display">\[
\begin{aligned}
A_s &amp;= \frac{p_{\perp 1}}{\rho_1 v_1^2} \\
A_m &amp;= \frac{1}{M_A^2}
\end{aligned}
\]</span> where <span class="math inline">\(M_A\)</span> is the upstream Alfvén Mach number. For common solar wind conditions, both of these parameters are quite small (<span class="math inline">\(\sim 0.01\)</span>).</p>
<p>For shocks, the tangential components of the electric and magnetic fields are <em>coplanar</em> (<a href="#eq-shock_coplanarity">Equation&nbsp;<span>17.3</span></a>). Thus, the components of the magnetic field upstream of the shock are given as <span class="math inline">\(B_{n1} = B_1 \cos\theta_1\)</span> and <span class="math inline">\(B_{t1} = B_1 \sin\theta_1\)</span>, where <span class="math inline">\(\theta_1\)</span> is the angle between the magnetic field vector and the vector <span class="math inline">\(\hat{n}\)</span> normal to the discontinuity. Similarly, the components of the bulk velocity upstream of the shock are chosen as <span class="math inline">\(v_{n1} = v_1 \cos\alpha\)</span> and <span class="math inline">\(v_{t1} = B_1 \sin\alpha\)</span>, where α the angle between the bulk velocity and the normal component of the velocity. Furthermore, a parameter <span class="math inline">\(\lambda\)</span> is used to denote the pressure anisotropy <span class="math display">\[
\lambda = p_\perp / p_\parallel
\]</span> and another parameter <span class="math inline">\(r\)</span> is used to denote the ratio of density <span class="math display">\[
r \equiv \frac{\rho_2}{\rho_1} = \frac{v_{n1}}{v_{n2}}
\]</span></p>
<section id="perpendicular-shock" class="level3" data-number="17.2.1">
<h3 data-number="17.2.1" class="anchored" data-anchor-id="perpendicular-shock"><span class="header-section-number">17.2.1</span> Perpendicular Shock</h3>
<p>For a perpendicular shock, <span class="math inline">\(B_n = 0\)</span>, we have the conservation relations reduce to <span class="math display">\[
\begin{aligned}
\lfloor \rho v_n \rceil &amp;= 0 \\
\lfloor v_n\mathbf{B}_t \rceil &amp;= 0 \\
\lfloor p_\perp + \frac{B_t^2}{8\pi} + \rho v_n^2 \rceil &amp;= 0 \\
\lfloor \rho v_n \mathbf{v}_t \rceil &amp;= 0 \\
\lfloor \rho v_n\big( \frac{\epsilon}{\rho} + \frac{v^2}{2} + \frac{p_\perp}{\rho} + \frac{B_t^2}{4\pi \rho} \big) \rceil &amp;= 0
\end{aligned}
\]</span></p>
<p>The quantities downstream of the discontinuity are <span class="math display">\[
\begin{aligned}
B_{t2} &amp;= r B_{t1} \\
v_{t2} &amp;= v_{t1} \\
p_{\perp 2} &amp;= p_{\perp 1} + \frac{B_{t1}^2}{8\pi}(1-r^2) + \rho_1 v_{n1}^2\big( 1 - \frac{1}{r} \big)
\end{aligned}
\]</span></p>
<p>Substituting these into the energy equation leads to <span class="math display">\[
\begin{aligned}
2 \lambda_1(3\lambda_2 +1)\xi^3 − \lambda_1(4\lambda_2 +1)(2A_S + A_M +2)\xi^2 \\
+ \lambda_2[2\lambda_1(4A_S + 1 + 2A_M ) + 2A_S ]\xi + A_M \lambda_1 = 0
\end{aligned}
\]</span> where <span class="math inline">\(\xi = 1/r\)</span>.</p>
<p>Now we can do some simple estimations. Assume we have isotropic upstream solar wind with <span class="math inline">\(n = 2 \textrm{amu/cc}\)</span>, <span class="math inline">\(\mathbf{v} = [600, 0, 0] \textrm{km/s}\)</span>, <span class="math inline">\(\mathbf{B} = [0, 0, -5] \textrm{nT}\)</span> in GSM coordinates, and <span class="math inline">\(T = 5\times 10^5 \textrm{K}\)</span>. We want to estimate the downstream anisotropy given a density/tangential magnetic field jump of 3.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode jl code-with-copy"><code class="sourceCode julia"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>KeyNotes.<span class="fu">shock_estimation</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Another thing to note is that, if you set the jump ratio to 4 (maximum value when <span class="math inline">\(\gamma = 5/3\)</span>) in the above calculations, the downstream anisotropy will become 0.6. This indicates that under this set of upstream conditions, the jump ratio shall never be close to 4 if the anisotropy <span class="math inline">\(T_\perp/T_\parallel &gt; 1\)</span>!</p>
</section>
</section>
<section id="parallel-shock" class="level2" data-number="17.3">
<h2 data-number="17.3" class="anchored" data-anchor-id="parallel-shock"><span class="header-section-number">17.3</span> Parallel Shock</h2>
<p>From MHD or double adiabatic theory, parallel shocks are more special in that the magnetic field strength remains unchanged so the equations effectively describe pure gasdynamic solutions. <span class="citation" data-cites="kuznetsov2018parallel">(<a href="#ref-kuznetsov2018parallel" role="doc-biblioref">Kuznetsov and Osin 2018</a>)</span> presents a simplified solution in a 1D parallel shock case with parallel and perpendicular thermal energy heat fluxes <span class="math inline">\(S_\parallel\)</span> and <span class="math inline">\(S_\perp\)</span> included. Note again the original CGL theory assumes 0 heat fluxes.</p>
<p>However, as have been indicated in <a href="#sec-switch-shocks"><span>Section&nbsp;17.1.7</span></a>, this does not cover the real physics involved into parallel shocks which must be treated on the basis of kinetic theory and with the simulation tool at hand. These shocks possess an extended foreshock region with its own extremely interesting dynamics for both types of particles, electrons and ions, reaching from the foreshock boundaries to the deep interior of the foreshock. Based mostly on kinetic simulations, the foreshock is the region where dissipation of flow energy starts well before the flow arrives at the shock. This dissipation is caused by various instabilities excited by the interaction between the flow and the reflected particles that have escaped to upstream from the shock. Interaction between these waves and the reflected and accumulated particle component in the foreshock causes wave growth and steeping, formation of shocklets and pulsations and causes continuous reformation of the quasi-parallel shock that differs completely from quasi-perpendicular shock reformation. It is the main process of maintaining the quasi-parallel shock which by its nature principally turns out to be locally nonstationary and, in addition, on the small scale making the quasi-parallel shock close to becoming quasi-perpendicular for the electrons. This process can be defined as turbulent reformation, with transient phenonmena like hot flow anomalies, foreshock bubbles, and the generation of electromagnetic radiation. Foreshock physics is important for particle acceleration.</p>
<p>The turbulent nature implies that the quasi-parallel shock transition is less sharp than the quasi-perpendicular shock transition and thus less well defined; there exists an extended turbulent foreshock instead of a shock foot. This foreshock consists of an electron and an ion foreshock. The main population is a diffuse ion component. The turbulence in the foreshock is generated by the reflected and accelerated foreshock particle populations. An important point in quasi-parallel shock physics is the <em>reformation</em> of the shock which works completely differently from quasi-perpendicular shocks; here it is provided by upstream low-frequency electromagnetic waves excited by the diffuse ion component. Steeping of these waves during shockward propagation and addition of the large amplitude waves at the shock transition reforms the shock front. The old shock front is expelled downstream where it causes downstream turbulence. During the reformation process the shock becomes locally quasi-perpendicular for the ions supporting particle reflection.</p>
<section id="turbulent-reformation" class="level3" data-number="17.3.1">
<h3 data-number="17.3.1" class="anchored" data-anchor-id="turbulent-reformation"><span class="header-section-number">17.3.1</span> Turbulent Reformation</h3>
<div id="fig-parallel-shock-reformation" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="../images/parallel_shock_reformation.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;17.5: The patchwork model of <span class="citation" data-cites="schwartz1991parallel">Schwartz and David (<a href="#ref-schwartz1991parallel" role="doc-biblioref">1991</a>)</span> of a quasi-parallel supercritical shock reformation. Left: Magnetic pulsations (SLAMS) grow in the ion foreshock and are convected toward the shock where they accumulate, thereby causing formation of an irregular shock structure. Note also the slight turning of the magnetic field into a direction that is more perpendicular to the shock surface with the shock surface itself becoming very irregular. Right: The same model with the pulsations being generated in the relatively broad ULF-wave-unstable region in greater proximity to the ion-foreshock boundary. When the ULF waves evolve to large amplitude and form localised structures these are convected toward the shock, grow, steepen, overlap, accumulate and lead to the build up of the irregular quasi-parallel shock structure which overlaps into the downstream direction.</figcaption>
</figure>
</div>
<p>Lucek et al [2002] checked this expectation by determining the local shock-normal angle <span class="math inline">\(\theta_{Bn}\)</span> and comparing it with the prediction estimated from magnetic field measurements by the ACE spacecraft which was located farther out in the upstream flow. The interesting result is that during the checked time-interval of passage of the quasi-parallel shock the prediction for the shock normal was around <span class="math inline">\(20-30^o\)</span>, as expected for quasi-parallel shocks. However, this value just set a lower bound on the actually measured shock normal angle. The measured <span class="math inline">\(\theta_{Bn}\)</span> was highly fluctuating around much larger values and, in addition, showed a tendency to be close to <span class="math inline">\(90^o\)</span>. It strengthens the claim that quasi-parallel shocks are locally, on the small scale, very close to perpendicular shocks, a property that they borrow from the large magnetic waves by which they are surrounded. In fact, we may even claim that locally, on the small scale (<span class="math inline">\(\leq \mathcal{O}(d_i)\)</span>), quasi-parallel shocks are quasi-perpendicular.</p>
<p>Thus, the quasi-parallel shock is the result of a build-up from upstream waves which continuously reorganise and reform the shock. The shock transition region turns out to consist of many embedded magnetic pulsations (SLAMS) of very large amplitudes. These pulsations have steep flanks and quite irregular shape, exhibit higher frequency oscillations probably propagating in the whistler mode while sitting on the feet or shoulders of the pulsations.</p>
<p>Another interesting property of magnetic pulsations in the shock transition region is the electric cross-SLAMS potential, which corresponds to a steep pressure gradient. The pulsations are subject to a fairly large number of high frequency, Debye scale structures in the electric field. These intense nonlinear electrostatic electron plasma waves indicates that the quasi-parallel shocks are sources of electron acceleration into beams which are capable to move upstream along the magnetic field over a certain distance and excite electron plasma waves at intensity high enough to enter into the nonlinear regime, forming solitons and electron holes (BGK modes). This is possible only if quasi-parallel shocks are quasi-perpendicular as well on the electron scale.</p>
</section>
<section id="parallel-shock-particle-reflection" class="level3" data-number="17.3.2">
<h3 data-number="17.3.2" class="anchored" data-anchor-id="parallel-shock-particle-reflection"><span class="header-section-number">17.3.2</span> Parallel Shock Particle Reflection</h3>
<p>There are two possible mechanisms:</p>
<ul>
<li>A quasi-parallel shock is capable of generating a large cross-shock potential, or it is capable of stochastically – or nearly stochastically – scattering ions in the shock transition region in pitch angle and energy in such a way that part of the incoming ion distribution can escape upstream.</li>
<li>On a scale that affects the ion motion, a quasi-parallel shock close to the shock transition becomes sufficiently quasi-perpendicular that ions are reflected in the same way as if they encountered a quasi-perpendicular shock.</li>
</ul>
</section>
</section>
<section id="instabilities-and-waves" class="level2" data-number="17.4">
<h2 data-number="17.4" class="anchored" data-anchor-id="instabilities-and-waves"><span class="header-section-number">17.4</span> Instabilities and Waves</h2>
<p>In the context of collisionless shocks the instabilities of interest can be divided into two classes. The first class contains those waves which can grow themselves to become a shock. It is clear that these waves will be of low frequency and comparably large scale because otherwise they would not evolve into a large macroscopic shock. The primary candidates are magnetosonic, Alfvén and whistler modes. A number of waves can form secondarily after an initial seed shock ramp and grow in some way out of one of these wave modes: these are ion modes which have now been identified to be responsible for structuring, shaping and reforming the shock. In fact real oblique shocks — which are the main class of shocks in interplanetary space and probably in all space and astrophysical objects — cannot survive without the presence of these ion waves which can therefore be considered the wave modes that really produce shocks in a process of taking and giving between shock and waves.</p>
<p>The second class includes waves that accompany the shock and provide anomalous transport coefficients like anomalous collision frequencies, friction coefficients, heat conductivity and viscosity. These waves are also important for the shock as they contribute to entropy generation and dissipation. However, they are not primary in the sense that they are not shock-forming waves.</p>
<p>Among them there is another group that only carries away energy and information from the shock. These are high-frequency waves, mostly electrostatic in nature, produced by electrons or when electromagnetic they are in the free-space radiation modes. In the latter case they carry the information from remote objects as radiation in various modes, radio or x-ray to Earth, informing of the existence of a shock. In interplanetary space it is only radio waves which fall into this group as the radiation measure of the heliospheric shocks is too small to map them into x-rays.</p>
<p>Here we restrict mostly to low frequency EM waves in warm plasma, <span class="math inline">\(\omega\le \omega_{ci}\)</span>, while only mention the high frequency EM waves in the end. Such waves are excited by plasma streams or kinetic anisotropies in one or the other way. A simple summary is given in <a href="#tbl-shock-waves">Table&nbsp;<span>17.2</span></a>.</p>
<div id="tbl-shock-waves" class="anchored">
<table class="table">
<caption>Table&nbsp;17.2: Types of instabilities and waves related to shocks</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 20%">
<col style="width: 21%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Mode</th>
<th style="text-align: center;">Wave Type</th>
<th style="text-align: center;">Handedness</th>
<th style="text-align: center;">Other Properties</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Firehose</td>
<td style="text-align: center;">Alfvén</td>
<td style="text-align: center;">left</td>
<td style="text-align: center;">Parallel prefered anisotropy</td>
</tr>
<tr class="even">
<td style="text-align: center;">Ion-Ion Beam</td>
<td style="text-align: center;">Fast</td>
<td style="text-align: center;">right</td>
<td style="text-align: center;">Cool beam</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Ion cyclotron</td>
<td style="text-align: center;">Alfvén</td>
<td style="text-align: center;">left</td>
<td style="text-align: center;">Warm beam</td>
</tr>
<tr class="even">
<td style="text-align: center;">KAW</td>
<td style="text-align: center;">Alfvén</td>
<td style="text-align: center;">right</td>
<td style="text-align: center;">Electron, parallel electric field</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Whistler</td>
<td style="text-align: center;">Alfvén</td>
<td style="text-align: center;">right</td>
<td style="text-align: center;">Hall term, electron</td>
</tr>
</tbody>
</table>
</div>
<section id="ion-instabilities-omega-leq-omega_ci" class="level3" data-number="17.4.1">
<h3 data-number="17.4.1" class="anchored" data-anchor-id="ion-instabilities-omega-leq-omega_ci"><span class="header-section-number">17.4.1</span> Ion Instabilities <span class="math inline">\(\omega \leq \omega_{ci}\)</span></h3>
<section id="firehose-mode" class="level4" data-number="17.4.1.1">
<h4 data-number="17.4.1.1" class="anchored" data-anchor-id="firehose-mode"><span class="header-section-number">17.4.1.1</span> Firehose mode</h4>
<p>The simplest instability known which distorts the magnetic field by exciting Alfvén waves that propagate along the magnetic field is the firehose mode. The wave excited are ordinary Alfvén waves, however, and are not suited for shock formation.</p>
<p>When the ion beam is fast and cold it does not go into resonance because its velocity is too high. In this case all ions participate in a nonresonant instability which in fact is a thermal firehose mode where the ion beam has sufficient energy to shake the field line. This mode propagates antiparallel to the ion beam, has small phase speed and negative helicity. This mode has large growth rate for large <span class="math inline">\(n_b / n_e\)</span> and <span class="math inline">\(v_b / v_A\)</span> simply because then there are many beam ions and the centrifugal force is large while the beam velocity lies outside any resonant wave speed. It is trivial that this instability becomes stronger when the ion beam is composed of heavier ions as the larger mass of these increases the centrifugal force effect.</p>
</section>
<section id="kinetic-alfvén-waves" class="level4" data-number="17.4.1.2">
<h4 data-number="17.4.1.2" class="anchored" data-anchor-id="kinetic-alfvén-waves"><span class="header-section-number">17.4.1.2</span> Kinetic Alfvén waves</h4>
<p>KAWs (<a href="wave.html#sec-kaw"><span>Section&nbsp;7.8.4</span></a>) possess a finite <span class="math inline">\(E_\parallel\)</span> which can accelerate electrons; in the other way, electron moving along the magnetic field in the opposite direction become retarded and feed their energy into KAWs.</p>
<p>Normally this is likely to be a minor effect, as the interaction of ions which are reflected from a solitary pulse and move back upstream ahead of the pulse will cause a stronger instability. The reflected ions will represent a beam that is moving against the initial plasma inflow which by itself is another ion beam neutralised by the comoving electrons. The free energy presented in the two counter-streaming beams leads to various instabilities as viewed by <span class="citation" data-cites="gary1993theory">Gary (<a href="#ref-gary1993theory" role="doc-biblioref">1993</a>)</span>.</p>
</section>
<section id="kinetic-growth-rate" class="level4" data-number="17.4.1.3">
<h4 data-number="17.4.1.3" class="anchored" data-anchor-id="kinetic-growth-rate"><span class="header-section-number">17.4.1.3</span> Kinetic growth rate</h4>
<p>At low frequencies it suffices for our purposes of understanding shock physics to deal with a three-component plasma consisting of two ion species and one neutralising electron component which we assume to follow a Maxwellian (thermal) velocity distribution. Moreover, we assume that the drifting ion components are Maxwellians as well. In conformity with the above remarks on a resonant instability we assume that the dominant ion component has large density <span class="math inline">\(n_i\gg n_b\)</span>, and the second component represents a weak fast beam of density <span class="math inline">\(n_b\)</span> propagating on the ion-electron background with velocity <span class="math inline">\(v_b \gg v_i \approx = 0\)</span>. Following <span class="citation" data-cites="gary1993theory">Gary (<a href="#ref-gary1993theory" role="doc-biblioref">1993</a>)</span> it is convenient to distinguish the three regimes:</p>
<ol type="1">
<li>cool beams (<span class="math inline">\(0&lt;v&lt;v_b\)</span>)</li>
<li>warm beams (<span class="math inline">\(v\sim v_b\)</span>)</li>
<li>hot beams (<span class="math inline">\(v\gg v_b\)</span>)</li>
</ol>
<p><a href="#fig-shock_instability_driver">Figure&nbsp;<span>17.6</span></a> shows the beam configurations for these three cases and the location of the wave resonances respectively the position of the unstable frequencies.</p>
<div id="fig-shock_instability_driver" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="../images/shock_instability_driver.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;17.6: The three cases of ion beam-plasma interaction and the location of the unstable frequencies. Shown is the parallel (reduced) distribution function <span class="math inline">\(F_i(k_\parallel v_\parallel)\)</span>, where for simplicity the (constant) parallel wavenumber <span class="math inline">\(k_\parallel\)</span> has been included into the argument. Right handed resonant modes (RH) are excited by a cool not too fast beam. When the beam is too fast the interaction becomes nonresonant. When the beam is hot, a resonant left hand mode (LH) is excited. In addition the effect of temperature anisotropy is shown when a plateau forms on the distribution function <span class="citation" data-cites="gary1993theory">(after <a href="#ref-gary1993theory" role="doc-biblioref">Gary 1993</a>)</span>.</figcaption>
</figure>
</div>
</section>
<section id="cold-ion-beam-right-hand-instability" class="level4" data-number="17.4.1.4">
<h4 data-number="17.4.1.4" class="anchored" data-anchor-id="cold-ion-beam-right-hand-instability"><span class="header-section-number">17.4.1.4</span> Cold Ion Beam: Right-Hand Instability</h4>
<p>Assume that the ion beam is thermally isotropic and cool in the above sense, i.e.&nbsp;its velocity relative to the bulk plasma is faster than its thermal speed. In this case a right-handed resonant instability occurs. In the absence of a beam <span class="math inline">\(v_b=0\)</span> the parallel propagating mode is a right-circularly polarised magnetosonic wave propagating on the lowest frequency whistler dispersion branch with <span class="math inline">\(\omega\approx k_\parallel v_A\)</span>. In presence of a drift this wave becomes unstable, and the fastest growing frequency is at frequency <span class="math inline">\(\omega \simeq k_\parallel v_b - \omega_{ci}.\)</span> This mode propagates parallel to the beam, because <span class="math inline">\(\omega&gt;0\)</span>, <span class="math inline">\(k_\parallel &gt; 0\)</span>, and <span class="math inline">\(v_b &gt; 0\)</span>. The numerical solution of this instability for densities <span class="math inline">\(0.01 \le n_b/n_i \le 0.1\)</span> at the wave-number <span class="math inline">\(k_\parallel\)</span> of fastest growth rate identifies a growth rate of the order of the wave frequency <span class="math inline">\(\gamma\sim\omega\)</span> and <span class="math display">\[
\gamma_m \simeq \omega_{ci}\left( \frac{n_b}{n_e} \right)^{1/3}
\]</span> for the maximum growth rate <span class="math inline">\(\gamma_m\)</span>, where <span class="math inline">\(n_e = n_i + n_b\)</span> is the total density from quasi-neutrality. This instability drives waves propagating together with the beam in the direction of the ion beam on the plasma background which has been assumed at rest. If applied for instance, to shock reflected ions then for 2% reflected ions the maximum growth rate is <span class="math inline">\(\gamma_m\sim 0.2\omega_{ci}\)</span>, and <span class="math inline">\(v_b\sim 1.2 \omega_{ci}/k_\parallel\)</span>, <span class="math inline">\(k_\parallel\sim 0.2 \omega_{ci}/v_A\)</span> which gives <span class="math inline">\(v_b \sim 6 v_A\)</span>. In the solar wind the Alfvén velocity is about <span class="math inline">\(v_A ≈ 30\,\mathrm{km/s}\)</span>. Hence the velocity difference between shock reflected ions and solar wind along the magnetic field should be roughly <span class="math inline">\(\sim 180\,\mathrm{km/s}\)</span>.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> The thermal velocity of the ion beam must thus be substantially less than this value, corresponding to a thermal beam energy less than <span class="math inline">\(T_b \ll 100\,\mathrm{eV}\)</span> which in the solar wind, for instance, is satisfied near the tangential field line. The solar wind travels at 300–1200 km/s. Complete reflection should produce beam speeds twice these values.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<p>The cyclotron resonance condition associated with the generated fast magnetosonic mode is <span class="math display">\[
\omega = v_b k_\parallel - \omega_{ci}
\]</span> where <span class="math inline">\(v_b\)</span> is the beam velocity and <span class="math inline">\(\omega_{ci}\)</span> the ion gyrofrequency. It can be approximated as <span class="math inline">\(\omega=v_A k_\parallel\)</span>.</p>
</section>
<section id="warm-ion-beam-left-hand-instability" class="level4" data-number="17.4.1.5">
<h4 data-number="17.4.1.5" class="anchored" data-anchor-id="warm-ion-beam-left-hand-instability"><span class="header-section-number">17.4.1.5</span> Warm Ion Beam: Left-Hand Instability</h4>
<p>The above instability is present when the ion beam is rather cold. When the temperature of the ion beam increases and the background ions remain to be cold, then beam ions appear on the negative velocity side of the bulk ion distribution and go into resonance there with the left-hand polarised ion-Alfvén wave. Their maximum growth rate is a fraction of the growth rate of the right-hand low frequency whistler mode.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> Nevertheless it can excite the Alfvén-ion cyclotron wave which also propagates parallel to the beam. For this instability the beam velocity must exceed the Alfvén speed <span class="math inline">\(v_b &gt; v_A\)</span>.</p>
<p>At oblique propagation both the right and left hand instabilities have smaller growth rates. But interestingly, it has been shown [Goldstein+, 1985] that the fastest growing modes then appear for oblique <span class="math inline">\(\mathbf{k}\)</span> and harmonics of the ion cyclotron frequency <span class="math inline">\(\omega\sim n\omega_{ci}, n=1,2,...\)</span>.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
</section>
</section>
<section id="electron-instabilities-and-radiation-omega-sim-omega_pe" class="level3" data-number="17.4.2">
<h3 data-number="17.4.2" class="anchored" data-anchor-id="electron-instabilities-and-radiation-omega-sim-omega_pe"><span class="header-section-number">17.4.2</span> Electron Instabilities and Radiation <span class="math inline">\(\omega \sim \omega_{pe}\)</span></h3>
<p>Other than ion beam excited instabilities electron-beam instabilities are not involved in direct shock formation (unless the electron beams are highly relativistic which in the entire heliosphere is not the case). The reason is that the frequencies of electron instabilities are high. However, just because of this reason they are crucial in anomalous transport being responsible for anomalous collision frequencies and high frequency field fluctuations. The reason is that the high frequency waves lead to energy loss of the electrons retarding them while for the heavier ions they represent a fluctuating background scattering them. In this way high frequency waves may contribute to the basic dissipation in shocks even though this dissipation for supercritical shocks will not be sufficient to maintain a collisionless shock or even to create a shock under collisionless conditions. This is also easy to understand intuitively, because the waves need time to be created and to reach a substantial amplitude. This time in a fast stream is longer than the time the stream needs to cross the shock. So waves will not accumulate there; rather the fast stream will have convected them downstream long before they have reached substantial amplitudes for becoming important in scattering.</p>
<p>When we are going to discuss electromagnetic waves which can be excited by electrons we also must keep in mind that such waves can propagate only when there is an electromagnetic dispersion branch in the plasma under consideration. These electromagnetic branches in <span class="math inline">\((\omega,\mathbf{k})\)</span>-space are located at frequencies below the electron cyclotron frequency <span class="math inline">\(\omega_{ce}\)</span>. The corresponding branch is the whistler mode branch. Electrons will (under conditions prevailing at shocks) in general not be able to excite electromagnetic modes at higher frequencies than <span class="math inline">\(\omega_{ce}\)</span>. We have seen before that ion beams have been able to excite whistlers at low frequencies but above the ion-cyclotron frequency. This was possible only because of the presence of the high frequency electron whistler branch as a channel for wave propagation. EM waves excited by electrons propagate on the whistler branch or its low frequency Alfvénic extension, both of which are right-handed. They also excite a variety of electrostatic emissions.</p>
</section>
<section id="whistlers" class="level3" data-number="17.4.3">
<h3 data-number="17.4.3" class="anchored" data-anchor-id="whistlers"><span class="header-section-number">17.4.3</span> Whistlers</h3>
<p><span class="citation" data-cites="gary1993theory">Gary (<a href="#ref-gary1993theory" role="doc-biblioref">1993</a>)</span> has investigated the case of whistler excitation by an electron beam. He finds from numerical solution of the full dispersion relation including an electron beam in parallel motion that with increasing beam velocity <span class="math inline">\(v_b\)</span> the real frequency of the unstable whistler decreases, i.e.&nbsp;the unstably excited whistler shifts to lower frequencies on the whistler branch while remaining in the whistler range <span class="math inline">\(\omega_{ci} &lt; \omega &lt; \omega_{ce}\)</span>. Both the background electrons and beam electrons contribute resonantly. The most important finding is that the whistler mode for sufficiently large <span class="math inline">\(\beta_i \sim 1\)</span> (which means low magnetic field), <span class="math inline">\(n_b/n_e\)</span> and <span class="math inline">\(T_b/T_e\)</span> has the lowest beam velocity threshold when compared with the electrostatic electron beam instabilities as shown in <a href="#fig-shock_whistler_instability">Figure&nbsp;<span>17.7</span></a>. This finding implies that in a relatively high-β plasma a moderately dense electron beam will first excite whistler waves. In the shock environment the conditions for excitation of whistlers should thus be favourable whenever an electron beam propagates across the plasma along the relatively weak magnetic field. The electrons in resonance satisfy <span class="math inline">\(v_\parallel = (\omega - \omega_{ce})/k_\parallel\)</span> and, because <span class="math inline">\(\omega \ll \omega_{ce}\)</span> the resonant electrons move in the direction opposite to the beam. Enhancing the beam temperature increases the number of resonant electrons thus feeding the instability.</p>
<p>On the other hand, increasing the beam speed shifts the particles out of resonance and decreases the instability. Hence for a given beam temperature the whistler instability has a maximum growth rate a few times the ion cyclotron frequency.</p>
<div id="fig-shock_whistler_instability" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="../images/beam_whistler_stability.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;17.7: The regions of instability of the electron beam excited whistler mode in density and beam velocity space for two different β compared to the ion acoustic and electron beam modes. Instability is above the curves. The whistler instability has the lowest threshold in this parameter range <span class="citation" data-cites="gary1993theory">(after <a href="#ref-gary1993theory" role="doc-biblioref">Gary 1993</a>)</span>.</figcaption>
</figure>
</div>
</section>
</section>
<section id="shock-particle-reflection" class="level2" data-number="17.5">
<h2 data-number="17.5" class="anchored" data-anchor-id="shock-particle-reflection"><span class="header-section-number">17.5</span> Shock Particle Reflection</h2>
<p>The process of particle reflection from a shock wave is one of the most important processes in the entire physics of collisionless shocks. However, the mechanism of particle reflection has not yet been fully illuminated.</p>
<p>Particle reflection is required in supercritical shocks as it is the only process that can compensate for the incapability of dissipative processes inside the shock ramp to digest the fast inflow of momentum and energy into the shock. Shock particle reflection is not dissipative by itself even though in a fluid picture which deals with moments of the distribution function it can be interpreted as kind of an ion viscosity, i.e.&nbsp;it generates an anomalous viscosity coefficient which appears as a factor in front of the second derivative of the ion velocity in the ionic equation of motion. As such it also appears in the ion heat-transport equation. The kinematic ion viscosity can be expressed as <span class="math display">\[
\mu_\mathrm{vis} = m_i n \nu_i \lambda_\mathrm{mfp} \simeq P_i / 2\omega_{ci}
\]</span> through the ion pressure <span class="math inline">\(P_i\)</span> and the ion-cyclotron frequency <span class="math inline">\(\omega_{ci}\)</span> when replacing the mean free path through the ion gyro-radius. In this sense shock particle reflection constitutes by itself a very efficient non-dissipative dissipation mechanism. However, its direct dissipative action is to produce real dissipation as far as possible upstream of the shock in order to dissipate as much energy of motion as remains to be in excess after formation of a shock ramp, dissipation inside the ramp, and reflection of ion back upstream. The shock does this by inhibiting a substantial fraction of inflow ions to pass across the shock from upstream into the downstream region. It is sending these ions back into the upstream region where they cause a violently unstable upstream ion beam-plasma configuration which excites a large amplitude turbulent wave spectrum that scatters the uninformed plasma inflow, heats it and retards it down to the Mach number range that can be digested by the shock. In this way the collisionless shock generates a shock transition region that extends far upstream with the shock ramp degrading to the role of playing a subshock at the location where the ultimate decrease of the Mach number from upstream to downstream takes place.</p>
<p>Shock reflection has another important effect on the shock as the momentum transfer from the reflected particle component to the shock retards the shock in the region of reflection thereby decreasing the effective Mach number of the shock.</p>
<section id="specular-reflection" class="level3" data-number="17.5.1">
<h3 data-number="17.5.1" class="anchored" data-anchor-id="specular-reflection"><span class="header-section-number">17.5.1</span> Specular Reflection</h3>
<p>Specular reflection of ions from a shock front is the simplest case to be imagined. It requires that the ions experience the shock ramp as an impenetrable wall. This can be the case when the shock itself contains a positive reflecting electric potential which builds up in front of the approaching ion. Generation of this electric potential is not clarified yet. In a very naive approach one assumes that in flowing magnetised plasma a potential wall is created as the consequence of charge separation between electrons and ions in penetrating the shock ramp. It occurs over a scale typically of the spatial difference between an ion and an electron gyro-radius, because in the ideal case the electrons, when running into the shock ramp, are held temporarily back in the steep magnetic field gradient over this distance while the ions feel the magnetic gradient only over a scale longer than their gyro-radius and thus penetrate deeper into the shock transition.</p>
<div id="fig-shock_specular_reflection" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="../images/shock_specular_reflection.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;17.8: The two cases of shock reflection. Left: Reflection from a potential well <span class="math inline">\(\Phi(x)\)</span>. Particles of energy higher than the potential energy <span class="math inline">\(e\Phi\)</span> can pass while lower energy particles become reflected. Right: Reflection from the perpendicular shock region at a curved shock wave as the result of magnetic field compression. Particles move toward the shock like in a magnetic mirror bottle, experience the repelling mirror force and for large initial pitch angles are reflected back upstream.</figcaption>
</figure>
</div>
<ul>
<li>Reflection from Shock Potential</li>
</ul>
<p>Due to this simplistic picture the shock ramp should contain a steep increase in the electric potential <span class="math inline">\(\Delta\Phi\)</span> which will reflect any ion which has less kinetic energy <span class="math inline">\(m_i V_N^2/2 &lt; e\Delta\Phi\)</span> (<a href="#fig-shock_specular_reflection">Figure&nbsp;<span>17.8</span></a>).</p>
<ul>
<li>Mirror Reflection</li>
</ul>
<p>Another simple possibility for particle reflection from a shock ramp in magnetised plasma is mirror reflection. An ion approaching the shock has components <span class="math inline">\(v_{i\parallel}\)</span>. Assume a curved shock like Earth’s bow shock. Close to its perpendicular part where the upstream magnetic field becomes tangential to the shock the particles approaching the shock with the stream and moving along the magnetic field with their parallel velocities experience a mirror magnetic field configuration that results from the converging magnetic field lines near the perpendicular point (<a href="#fig-shock_specular_reflection">Figure&nbsp;<span>17.8</span></a>). Conservation of the magnetic moment <span class="math inline">\(\mu = T_{i\perp}/B\)</span> implies that the particles become heated adiabatically in the increasing field; they also experience a reflecting mirror force <span class="math inline">\(-\mu \nabla_\parallel B\)</span> which tries to keep ions away from entering the shock along the magnetic field. Particles will mirror at the perpendicular shock point and return upstream when their pitch angle becomes 90◦ at this location. (??? Leroy &amp; Mangeney, 1984; Wu, 1984)</p>
<p>Specular reflection from shocks is the extreme case of shock particle reflection. Other mechanisms like turbulent reflection are, however, not well elaborated and must in any case be investigated with the help of numerical simulations.</p>
</section>
<section id="consequences-of-shock-reflection" class="level3" data-number="17.5.2">
<h3 data-number="17.5.2" class="anchored" data-anchor-id="consequences-of-shock-reflection"><span class="header-section-number">17.5.2</span> Consequences of Shock Reflection</h3>
<p>How far the reflected ions return upstream depends on the direction of the magnetic field with respect to the shock, i.e.&nbsp;on the shock normal angle <span class="math inline">\(\theta_{Bn}\)</span>. For perpendicular shocks the reflected ions only pass just one gyro-radius back upstream. Seeing the convection electric field <span class="math inline">\(\mathbf{E} = -\mathbf{v}_\mathrm{flow}\times\mathbf{B}\)</span> they become accelerated along the shock forming a current, the velocity of which in any case exceeds the inflow velocity (which is zero in the perpendicular direction) and for sufficiently cold ions also the ion acoustic velocity <span class="math inline">\(c_{ia}\)</span> in which case the ion-beam plasma instability will be excited in the shock foot region where the ion current flows. This may generate anomalous collision in the shock foot region. Moreover, since the excited waves accelerate electrons along the magnetic field other secondary instabilities can arise as well.</p>
<p>In quasi-perpendicular and oblique shocks the ions can escape along the magnetic field. In this case an ion two-stream situation arises between the upstream beam and the plasma inflow with the consequence of excitation of a variety of electromagnetic and electrostatic instabilities. In addition, however, an ion-electron two-stream situation is caused between the upstream ions and the inflow electrons which because of the large upstream electron temperatures probably excites mainly ion-acoustic modes but can also lead to Buneman two-stream mode excitation. These modes contribute to turbulence in the upstream foreshock region creating a weakly dissipative state in the foreshock where the plasma inflow becomes informed about the presence of the shock. The electromagnetic low frequency instabilities on the other hand, which are excited in this region, will grow to large amplitude, form localised structures and after being convected by the main flow towards the shock ramp interact with the shock and modify the shock profile or even contribute to shock formation and shock regeneration.</p>
</section>
</section>
<section id="foreshock-transients" class="level2" data-number="17.6">
<h2 data-number="17.6" class="anchored" data-anchor-id="foreshock-transients"><span class="header-section-number">17.6</span> Foreshock Transients</h2>
<p>This section provides a list and a very short description of foreshock transients based on observations including hot flow anomalies (HFAs), spontaneous hot flow anomalies (SHFAs), foreshock bubbles (FBs), foreshock cavities, foreshock cavitons, foreshock compressional boundaries, density holes, and Short Large-Amplitude Magnetic structures (SLAMs). <a href="#tbl-foreshock-transient">Table&nbsp;<span>17.3</span></a> shows a comparison of their characteristics after <span class="citation" data-cites="zhang2022dayside">(<a href="#ref-zhang2022dayside" role="doc-biblioref">Zhang et al. 2022</a>)</span>.</p>
<div id="tbl-foreshock-transient" class="tbl-parent quarto-layout-panel anchored">
<div class="panel-caption table-caption">
<p>Table&nbsp;17.3: Comparison of foreshock transient phenomena at the bow shocks</p>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div id="tbl-foreshock-transient-1" class="quarto-layout-cell quarto-layout-cell-subref anchored" data-ref-parent="tbl-foreshock-transient" style="flex-basis: 100.0%;justify-content: center;">
<table class="table">
<caption>(a) Basic foreshock transient properties</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Depletion in n and B</th>
<th style="text-align: center;">Compression in n and B</th>
<th style="text-align: center;">Presence of suprathermal ions</th>
<th style="text-align: center;">Flow deflection</th>
<th style="text-align: center;">Plasma heating</th>
<th style="text-align: center;">Associated with an IMF discontinuity</th>
<th style="text-align: center;">Duration</th>
<th style="text-align: center;">Scale size</th>
<th style="text-align: center;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">HFA</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">At edges</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Strong</td>
<td style="text-align: center;">Strong</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;"><span class="math inline">\(10 - 10^2\)</span> s</td>
<td style="text-align: center;"><span class="math inline">\(\mathcal{O}(R_E)\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">SHFA</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">At edges</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Strong</td>
<td style="text-align: center;">Strong</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;"><span class="math inline">\(10 - 10^2\)</span> s</td>
<td style="text-align: center;"><span class="math inline">\(\mathcal{O}(R_E)\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">FB</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Only on the upstream edge</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Strong</td>
<td style="text-align: center;">Strong</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;"><span class="math inline">\(10 - 10^2\)</span> s</td>
<td style="text-align: center;"><span class="math inline">\(\mathcal{O}(R_E)\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">Cavity</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">At edges</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Weak</td>
<td style="text-align: center;">Modest</td>
<td style="text-align: center;">Sometimes</td>
<td style="text-align: center;"><span class="math inline">\(10 - 10^2\)</span> s</td>
<td style="text-align: center;"><span class="math inline">\(\mathcal{O}(R_E)\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Caviton</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">At edges</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Weak</td>
<td style="text-align: center;">Weak</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;"><span class="math inline">\(10 - 60\)</span> s</td>
<td style="text-align: center;"><span class="math inline">\(\mathcal{O}(R_E)\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">FCB</td>
<td style="text-align: center;">Yes on the turbulent side</td>
<td style="text-align: center;">At edges</td>
<td style="text-align: center;">Maybe</td>
<td style="text-align: center;">Weak</td>
<td style="text-align: center;">Weak</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;"><span class="math inline">\(10 - 10^2\)</span> s</td>
<td style="text-align: center;"><span class="math inline">\(\mathcal{O}(R_E)\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Density Hole</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">At edges</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Sometimes</td>
<td style="text-align: center;">Sometimes</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;"><span class="math inline">\(1 - 60\)</span> s</td>
<td style="text-align: center;"><span class="math inline">\(\mathcal{O}(R_E)\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">SLAMS</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Maybe</td>
<td style="text-align: center;">Sometimes</td>
<td style="text-align: center;">Sometimes</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;"><span class="math inline">\(1 - 60\)</span> s</td>
<td style="text-align: center;"><span class="math inline">\(&lt;0.5\, R_E\)</span></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div id="tbl-foreshock-transient-2" class="quarto-layout-cell quarto-layout-cell-subref anchored" data-ref-parent="tbl-foreshock-transient" style="flex-basis: 100.0%;justify-content: center;">
<table class="table">
<caption>(b) Foreshock transients generation mechanisms</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 85%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Generation mechanism</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">HFA</td>
<td style="text-align: left;">Interaction of IMF discontinuities with the bow shock</td>
</tr>
<tr class="even">
<td style="text-align: left;">SHFA</td>
<td style="text-align: left;">Interaction of foreshock cavitons with the bow shock</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FB</td>
<td style="text-align: left;">Kinetic interactions between suprathermal, backstreaming ions and incident SW plasma with embedded IMF discontinuities that move through and alter the ion foreshock</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cavity</td>
<td style="text-align: left;">Antisunward moving slabs of magnetic field lines that connect to the bow shock that are sandwiched between broader regions of magnetic field lines that remain unconnected to the bow shock</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Caviton</td>
<td style="text-align: left;">Nonlinear interaction of ULF waves</td>
</tr>
<tr class="even">
<td style="text-align: left;">FCB</td>
<td style="text-align: left;">Backstreaming ions result in increased pressure within the foreshock region leading to its expansion against the pristine SW and the generation of FCBs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Density Hole</td>
<td style="text-align: left;">Possibly due to backstreaming particles interacting with the original SW</td>
</tr>
<tr class="even">
<td style="text-align: left;">SLAMS</td>
<td style="text-align: left;">Nonlinear wave steepening</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<section id="hot-flow-anomaly" class="level3" data-number="17.6.1">
<h3 data-number="17.6.1" class="anchored" data-anchor-id="hot-flow-anomaly"><span class="header-section-number">17.6.1</span> Hot Flow Anomaly</h3>
<p>HFAs are characterized by a low field strength and low density core with heated plasma and substantial flow deflection with sizes of several <span class="math inline">\(\mathrm{R}_\mathrm{E}\)</span>. HFAs are typically driven by a solar wind tangential discontinuity (TD) that intersects the bow shock with solar wind convection electric field pointing inward on at least one side of the TD. Such a TD can locally trap foreshock ions leading to the HFA formation while propagating along the bow shock surface. HFAs may accelerate particles efficiently through Fermi acceleration, i.e., bouncing between the converging HFA boundary and the bow shock. The observed energetic ions may also have escaped from the outer magnetosphere.</p>
<p>One of the most remarkable properties of HFAs is the strong deflection of the solar wind bulk flow which can be large enough that inside an HFA the flow can actually show a sunward component. A transient region of lower density in the solar wind interacting with the fast shock can cause the disruption of the fast shock and leads to a new shock that actually travels into the upstream direction with plasma behind this new shock having a much smaller momentum density and velocity than the original solar wind.</p>
</section>
<section id="spontaneous-hot-flow-anomaly" class="level3" data-number="17.6.2">
<h3 data-number="17.6.2" class="anchored" data-anchor-id="spontaneous-hot-flow-anomaly"><span class="header-section-number">17.6.2</span> Spontaneous Hot Flow Anomaly</h3>
<p>SHFAs have the same characteristics as HFAs except that they are not associated with any solar wind discontinuities. They form intrinsically in the quasi-parallel regime, likely due to the interaction between foreshock cavitons and the bow shock.</p>
<p>In order to distinguish SHFAs from cavitons in simulations, an additional empirical criterion of SHFA having <span class="math inline">\(\beta &gt; 10\)</span> in at least 60% of the transient region has been used. It is chosen in order to not make assumptions on the level of heating and flow deflection inside the transients. A value of 10 indicates that the transients are dominated by the plasma instead of the magnetic field, and it is significantly above the typical β in the surrounding foreshock (<span class="math inline">\(β \sim 1-4\)</span>).</p>
</section>
<section id="foreshock-bubble" class="level3" data-number="17.6.3">
<h3 data-number="17.6.3" class="anchored" data-anchor-id="foreshock-bubble"><span class="header-section-number">17.6.3</span> Foreshock Bubble</h3>
<p>When backstreaming foreshock ions interact with a solar wind rotational discontinuity (RD) that does not necessarily intersect the bow shock, FBs form upstream of the RD and convecting anti-sunward with it. Later observations and simulations found that TDs can also drive FBs. FBs are also characterized by a heated, tenuous core with significant flow deflection. Different from HFAs and SHFAs, the expansion of FBs is super-fast-magnetosonic and dominantly in the sunward direction. Because of the sunward super-fast-magnetosonic expansion, a shock forms upstream of the core, and the FB size in the expansion direction can reach 5-10 <span class="math inline">\(\mathrm{R}_\mathrm{E}\)</span>, larger than typical HFAs and SHFAs. In addition to their significant dynamic pressure perturbations, FBs are also efficient particle accelerators due to the presence of the shock (e.g., shock drift acceleration and Fermi acceleration as the shock converges towards the bow shock).</p>
</section>
<section id="foreshock-cavity" class="level3" data-number="17.6.4">
<h3 data-number="17.6.4" class="anchored" data-anchor-id="foreshock-cavity"><span class="header-section-number">17.6.4</span> Foreshock Cavity</h3>
<p>Foreshock cavities are characterized by low density, low field strength core regions with high density, high field strength compressional boundaries on two sides. But different from HFAs, the flow deflection inside foreshock cavities is rather weak and plasma heating is not significant. When slabs of magnetic field lines connected to the bow shock are bounded by broader regions of magnetic field lines that remain unconnected to the bow shock, only the slabs are filled with energized particles reflected from the bow shock. The presence of foreshock particles enhanced the thermal pressure, causing an expansion on two sides. Such an expansion decreases the plasma density and magnetic field strength inside the slabs and increases the density and field strength at two boundaries, i.e., a foreshock cavity forms.</p>
</section>
<section id="foreshock-caviton" class="level3" data-number="17.6.5">
<h3 data-number="17.6.5" class="anchored" data-anchor-id="foreshock-caviton"><span class="header-section-number">17.6.5</span> Foreshock Caviton</h3>
<p>Foreshock cavitons are also characterized by a core region with low density and field strength bounded by two boundaries with high density and field strength, without clear heating and flow deflection. Their sizes are about one <span class="math inline">\(\mathrm{R}_\mathrm{E}\)</span>. They form due to the nonlinear evolution of two types of waves: the parallel propagating right- or left-hand polarized waves and the obliquely propagating linearly polarized fast magnetosonic waves. Thus, foreshock cavitons are embedded in foreshock ULF waves, whereas foreshock cavities are isolated due to their different formation mechanisms.</p>
</section>
<section id="foreshock-compressional-boundary" class="level3" data-number="17.6.6">
<h3 data-number="17.6.6" class="anchored" data-anchor-id="foreshock-compressional-boundary"><span class="header-section-number">17.6.6</span> Foreshock Compressional Boundary</h3>
<p>FCBs have enhanced density and field strength. They occur at the boundary between the foreshock and the pristine solar wind. Because of the high thermal pressure due to the presence of foreshock ions, the foreshock region expands into the ambient pristine solar wind, leading to the formation of an FCB. FCBs are sometimes associated with local density and field strength depletion on their foreshock side. FCBs can form under either steady or nonsteady IMF conditions.</p>
</section>
<section id="slams-and-shocklets" class="level3" data-number="17.6.7">
<h3 data-number="17.6.7" class="anchored" data-anchor-id="slams-and-shocklets"><span class="header-section-number">17.6.7</span> SLAMS and Shocklets</h3>
<p>Short Large-Amplitude Magnetic Structures (SLAMS) are magnetic pulsations with amplitudes at least two times the ambient magnetic field strength. SLAMS have typical spatial scales up to many ion gyroradii (where the thermal ion gyroradius is typically 160 km in the solar wind) and grow rapidly with time scales of seconds. Shocklets are also magnetic structures (nonlinearly steepened magnetosonic waves), but differ from SLAMS in terms of amplitude, spatial scale, growth rate, and propagation angle.</p>
</section>
<section id="density-hole" class="level3" data-number="17.6.8">
<h3 data-number="17.6.8" class="anchored" data-anchor-id="density-hole"><span class="header-section-number">17.6.8</span> Density Hole</h3>
<p>Density holes are characterized by similarly shaped magnetic holes with enhanced density and field strength at one or both edges. The definition of density holes overlaps with HFAs, SHFAs, FBs, foreshock cavities, and foreshock cavitons, but in a broader sense. <span class="citation" data-cites="lu2022statistical">Lu et al. (<a href="#ref-lu2022statistical" role="doc-biblioref">2022</a>)</span> showed statistically that ∼66% of 411 density holes cannot be categorized by any of these foreshock transient types. Therefore, it is necessary to make density holes a separate category. A better definition of density holes is needed to definitely distinguish them from other foreshock transient types, which requires further studies. The formation could be due to the interaction between backstreaming particles and the original solar wind <span class="citation" data-cites="parks2006larmor">(<a href="#ref-parks2006larmor" role="doc-biblioref">Parks et al. 2006</a>)</span>.</p>
</section>
</section>
<section id="subcritical-shocks" class="level2" data-number="17.7">
<h2 data-number="17.7" class="anchored" data-anchor-id="subcritical-shocks"><span class="header-section-number">17.7</span> Subcritical Shocks</h2>
<p>Subcritical shocks have Mach numbers between 1 and <span class="math inline">\(M_c\)</span> which can be described by the combined action of dispersion and dissipation present in dispersive waves in collisionless plasmas. Subcritical shocks have been believed to be rare in space; they were mostly restrictedly associated to heavy mass loading of the solar wind as is the case in the vicinity of comets and Venus and Mars as the unmagnetised planets, in particular at Venus with its dense atmosphere. However, they might be much more frequent simply due to the properties of dispersive waves which nonlinearly are capable of steeping and evolving into shocks.</p>
<p>Evolution of subcritical shocks in the latter case is now quite well understood, even though the generation of anomalous resistance and anomalous dissipation below the critical Mach number still poses many unresolved problems. It is well established that the subcritical shock evolves through the various phases of steeping of a low frequency magnetosonic wave the character of which has been identified of being on the whistler mode branch. This steeping process is completely non-collisional. The modes propagate against the upstream flow, forming a train of localised wave modes where the steeping is produced by sideband generation of higher spatial harmonics all propagating (approximately) at the same phase (group) velocity such that their amplitudes are in phase and superimpose on the mother wave. When the gradient length of the leading wave packet becomes comparable to the dissipation scale <span class="math inline">\(L_d\)</span>, dissipation sets on. At this time the smaller scale higher harmonic sidebands either outrun the leading wave packet ending up as standing, spatially damped precursor wave modes in front of the shock, or forming a spatially damped trailing wake of the packet. This depends on whether the dispersion is convex or concave (sign of <span class="math inline">\(\partial^2 \omega /\partial k^2\)</span>). This dispersive effect limits the amplitude of the shock. At the same time the ramp is formed out of the wave packet by the dissipation generated inside the shock.</p>
<p>Generation of dissipation is most likely due to electron current instabilities of the shock ramp current on a scale that is shorter than the ion inertial scale. So far the instability has not yet been identified, but we have given strong arguments that it is the modified two stream instability which signs responsible. The anomalous collision rate is at the lower hybrid frequency in the shock ramp, quite high in this case and sufficient for providing the necessary dissipation for entropy generation, shock heating and compression. In addition, other small scale effects might occur which we have only given a hint on but not discussed in depth.</p>
</section>
<section id="location-of-shocks" class="level2" data-number="17.8">
<h2 data-number="17.8" class="anchored" data-anchor-id="location-of-shocks"><span class="header-section-number">17.8</span> Location of Shocks</h2>
<p>In the observation comparison paper <span class="citation" data-cites="slavin1981solar">(<a href="#ref-slavin1981solar" role="doc-biblioref">Slavin and Holzer 1981</a>)</span> for quasi-perpendicular shocks, they concluded that the variations in shock stand-off distance and shape are ordered by the sonic Mach number <span class="math inline">\(M_s\)</span> and not other Mach numbers involve magnetic field. In other words, they think the bow shock is a gasdynamic structure.</p>
<p>However, even in neutral fluid theory, the determination of shock location as well as shape is still an ongoing research. Imagine the simplest scenario where there is a static ball in the air with infinite mass. Assuming purely homogenous air with known density, velocity and pressure in the upstream, can you tell me the exact location of shock stand-off distance with pen and paper?</p>
<p>On top of that, the introduction of EM field complicates the story. Especially in the case of a parallel shock, the plasmas get “shocked” both upstream and downstream, and the stand-off distance of the shock may not be a single point theoretically. In some sense, normal magnetic field to the boundary “thickens” the shock front.</p>
</section>
<section id="earth-bow-shock" class="level2" data-number="17.9">
<h2 data-number="17.9" class="anchored" data-anchor-id="earth-bow-shock"><span class="header-section-number">17.9</span> Earth Bow Shock</h2>
<p>Using data from the AMPTE/IRM spacecraft, <span class="citation" data-cites="hill1995plasma">(<a href="#ref-hill1995plasma" role="doc-biblioref">Hill et al. 1995</a>)</span> have shown that the double adiabatic equations do not hold in the magnetosheath. Moreover, the thermal behaviour of the magnetosheath is studied by <span class="citation" data-cites="phan1996subsolar">(<a href="#ref-phan1996subsolar" role="doc-biblioref">Phan et al. 1996</a>)</span> using WIND spacecraft data. They report that most parts of the magnetosheath are marginally mirror unstable: electron observations showed <span class="math inline">\(T_{e\perp} / T_{e\parallel} \sim 1.3\)</span> in the magnetosheath.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-abraham1967shock" class="csl-entry" role="listitem">
Abraham-Shrauner, Barbara. 1967. <span>“Shock Jump Conditions for an Anisotropic Plasma.”</span> <em>Journal of Plasma Physics</em> 1 (3): 379–81. <a href="https://doi.org/10.1017/S0022377800003366">https://doi.org/10.1017/S0022377800003366</a>.
</div>
<div id="ref-balogh2013physics" class="csl-entry" role="listitem">
Balogh, André, and Rudolf A Treumann. 2013. <em>Physics of Collisionless Shocks: Space Plasma Shock Waves</em>. Springer Science &amp; Business Media. <a href="https://doi.org/10.1007/978-1-4614-6099-2">https://doi.org/10.1007/978-1-4614-6099-2</a>.
</div>
<div id="ref-cgl1956" class="csl-entry" role="listitem">
Chew, GF, ML Goldberger, and FE Low. 1956. <span>“The Boltzmann Equation and the One-Fluid Hydromagnetic Equations in the Absence of Particle Collisions.”</span> <em>Proceedings of the Royal Society of London. Series A. Mathematical and Physical Sciences</em> 236 (1204): 112–18. <a href="https://doi.org/10.1098/rspa.1956.0116">https://doi.org/10.1098/rspa.1956.0116</a>.
</div>
<div id="ref-erkaev2000solution" class="csl-entry" role="listitem">
Erkaev, NV, DF Vogl, and HK Biernat. 2000. <span>“Solution for Jump Conditions at Fast Shocks in an Anisotropic Magnetized Plasma.”</span> <em>Journal of Plasma Physics</em> 64 (5): 561–78. <a href="https://doi.org/10.1017/S002237780000893X">https://doi.org/10.1017/S002237780000893X</a>.
</div>
<div id="ref-gary1993theory" class="csl-entry" role="listitem">
Gary, S Peter. 1993. <em>Theory of Space Plasma Microinstabilities</em>. 7. Cambridge university press.
</div>
<div id="ref-hill1995plasma" class="csl-entry" role="listitem">
Hill, P, G Paschmann, RA Treumann, W Baumjohann, N Sckopke, and H Lühr. 1995. <span>“Plasma and Magnetic Field Behavior Across the Magnetosheath Near Local Noon.”</span> <em>Journal of Geophysical Research: Space Physics</em> 100 (A6): 9575–83. <a href="https://doi.org/10.1029/94JA03194">https://doi.org/10.1029/94JA03194</a>.
</div>
<div id="ref-hudson1970discontinuities" class="csl-entry" role="listitem">
Hudson, PD. 1970. <span>“Discontinuities in an Anisotropic Plasma and Their Identification in the Solar Wind.”</span> <em>Planetary and Space Science</em> 18 (11): 1611–22. <a href="https://doi.org/10.1016/0032-0633(70)90036-X">https://doi.org/10.1016/0032-0633(70)90036-X</a>.
</div>
<div id="ref-kuznetsov2018parallel" class="csl-entry" role="listitem">
Kuznetsov, VD, and AI Osin. 2018. <span>“On the Parallel Shock Waves in Collisionless Plasma with Heat Fluxes.”</span> <em>Physics Letters A</em> 382 (31): 2052–54. <a href="https://doi.org/10.1016/j.physleta.2018.05.029">https://doi.org/10.1016/j.physleta.2018.05.029</a>.
</div>
<div id="ref-lu2022statistical" class="csl-entry" role="listitem">
Lu, Xi, Hui Zhang, Terry Liu, Andrew Vu, Craig Pollock, and Boyi Wang. 2022. <span>“Statistical Study of Foreshock Density Holes.”</span> <em>Journal of Geophysical Research: Space Physics</em> 127 (4): e2021JA029981. <a href="https://doi.org/10.1029/2021JA029981">https://doi.org/10.1029/2021JA029981</a>.
</div>
<div id="ref-parks2006larmor" class="csl-entry" role="listitem">
Parks, GK, E Lee, F Mozer, M Wilber, E Lucek, I Dandouras, H Rème, et al. 2006. <span>“Larmor Radius Size Density Holes Discovered in the Solar Wind Upstream of Earth’s Bow Shock.”</span> <em>Physics of Plasmas</em> 13 (5): 050701. <a href="https://doi.org/10.1063/1.2201056">https://doi.org/10.1063/1.2201056</a>.
</div>
<div id="ref-phan1996subsolar" class="csl-entry" role="listitem">
Phan, TD, DE Larson, RP Lin, JP McFadden, KA Anderson, CW Carlson, RE Ergun, et al. 1996. <span>“The Subsolar Magnetosheath and Magnetopause for High Solar Wind Ram Pressure: WIND Observations.”</span> <em>Geophysical Research Letters</em> 23 (10): 1279–82. <a href="https://doi.org/10.1029/96GL00845">https://doi.org/10.1029/96GL00845</a>.
</div>
<div id="ref-schwartz1991parallel" class="csl-entry" role="listitem">
Schwartz, J., Steven, and Burgess David. 1991. <span>“Quasi-Parallel Shocks: A Patchwork of Three-Dimensional Structures.”</span> <em>Journal of Geophysical Research: Space Physics</em>. <a href="https://doi.org/10.1029/91GL00138">https://doi.org/10.1029/91GL00138</a>.
</div>
<div id="ref-slavin1981solar" class="csl-entry" role="listitem">
Slavin, James A, and Robert E Holzer. 1981. <span>“Solar Wind Flow about the Terrestrial Planets 1. Modeling Bow Shock Position and Shape.”</span> <em>Journal of Geophysical Research: Space Physics</em> 86 (A13): 11401–18. <a href="https://doi.org/10.1029/JA086iA13p11401">https://doi.org/10.1029/JA086iA13p11401</a>.
</div>
<div id="ref-zhang2022dayside" class="csl-entry" role="listitem">
Zhang, Hui, Qiugang Zong, Hyunju Connor, Peter Delamere, Gábor Facskó, Desheng Han, Hiroshi Hasegawa, et al. 2022. <span>“Dayside Transient Phenomena and Their Impact on the Magnetosphere and Ionosphere.”</span> <em>Space Science Reviews</em> 218 (5): 40. <a href="https://doi.org/10.1007/s11214-021-00865-0">https://doi.org/10.1007/s11214-021-00865-0</a>.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>I don’t quite understand this. From <a href="#fig-critical_mach_number_mhd_perp_shock">Figure&nbsp;<span>17.2</span></a>, it is clear that above the critical Mach number, <span class="math inline">\(V_{2n} &lt; c_{2ms}^+\)</span> is true.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>so it depends on the upstream sound speed?<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>for a parallel shock, the HT frame can be just itself; for a perpendicular shock, the HT frame can be chosen by shifting the velocity by <span class="math inline">\(\mathbf{v}_1\)</span> s.t. <span class="math inline">\(\mathbf{v}_1 = 0\)</span>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>This is a very strong indication that Alfvén waves are involved in switch-on/off shocks!<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>If the typical Vlasiator simulation values are used, <span class="math inline">\(B=5\,\mathrm{nT}\)</span>, <span class="math inline">\(n=10^6/\mathrm{cc}\)</span>, <span class="math inline">\(v_A = 109\,\mathrm{km/s}\)</span>, <span class="math inline">\(\Delta v \sim 650\,\mathrm{km/s}\)</span>.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>The statement in <span class="citation" data-cites="balogh2013physics">(<a href="#ref-balogh2013physics" role="doc-biblioref">Balogh and Treumann 2013</a>)</span> is hard to follow. Maybe what they tried to argue is that it is the perpendicular portion of the shock that creates these reflected ions and leads to the instability. Later in the book they argued that on a small scale quasi-parallel shocks become perpendicular.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>so literally the Alfvénic branch?<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>In the early Vlasiator paper 2014, the simulated RH growth rate is lower than theory, even though in a 1D3V almost parallel configuration.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../contents/solarwind.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Solar Wind</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../contents/magnetosphere.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Magnetosphere</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>