<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Key Notes in Plasma Physics - 25&nbsp; Tests</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../contents/appendix.html" rel="next">
<link href="../contents/hybrid.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Tests</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Key Notes in Plasma Physics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/henry2004y/KeyNotes/" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle sidebar-tool" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/about.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">About</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/introduction.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/math.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Math</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/single.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Single-Particle Motions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/fluid.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Plasmas as Fluid</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/diffres.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Diffusion and Resisvity</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/wave.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Waves</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/kinetic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Kinetic Theory</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/stability.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Stability</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/kmhd.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Kinetic MHD</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/gyrokinetics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Gyrokinetics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/flr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Field Line Resonance</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/nonlinear.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Nonlinear Effects</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/turbulence.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Turbulence</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/geometry.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Geometry</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/solarwind.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Solar Wind</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/shock.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Shock</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/magnetosphere.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Magnetosphere</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/ionosphere.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Ionosphere</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/radiationbelt.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Radiation Belt</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/aurora.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Aurora</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/boundary.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Boundary Conditions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/pic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Particle-in-Cell</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/hybrid.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Hybrid Methods</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/test.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Tests</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/appendix.html" class="sidebar-item-text sidebar-link">Appendix</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/references.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#unit-conversion" id="toc-unit-conversion" class="nav-link active" data-scroll-target="#unit-conversion"><span class="toc-section-number">25.0.1</span>  Unit Conversion</a></li>
  <li><a href="#errors" id="toc-errors" class="nav-link" data-scroll-target="#errors"><span class="toc-section-number">25.1</span>  Errors</a></li>
  <li><a href="#wave-tests" id="toc-wave-tests" class="nav-link" data-scroll-target="#wave-tests"><span class="toc-section-number">25.2</span>  Wave Tests</a>
  <ul class="collapse">
  <li><a href="#linear-wave" id="toc-linear-wave" class="nav-link" data-scroll-target="#linear-wave"><span class="toc-section-number">25.2.1</span>  Linear wave</a></li>
  <li><a href="#d-adiabatic-mhd-2" id="toc-d-adiabatic-mhd-2" class="nav-link" data-scroll-target="#d-adiabatic-mhd-2"><span class="toc-section-number">25.2.2</span>  3D Adiabatic MHD</a></li>
  <li><a href="#circularly-polarized-alfvén-wave" id="toc-circularly-polarized-alfvén-wave" class="nav-link" data-scroll-target="#circularly-polarized-alfvén-wave"><span class="toc-section-number">25.2.3</span>  Circularly polarized Alfvén wave</a></li>
  <li><a href="#light-wave" id="toc-light-wave" class="nav-link" data-scroll-target="#light-wave"><span class="toc-section-number">25.2.4</span>  Light wave</a></li>
  <li><a href="#firehose-instability" id="toc-firehose-instability" class="nav-link" data-scroll-target="#firehose-instability"><span class="toc-section-number">25.2.5</span>  Firehose instability</a></li>
  <li><a href="#mirror-mode-instability" id="toc-mirror-mode-instability" class="nav-link" data-scroll-target="#mirror-mode-instability"><span class="toc-section-number">25.2.6</span>  Mirror mode instability</a></li>
  </ul></li>
  <li><a href="#shock-tests" id="toc-shock-tests" class="nav-link" data-scroll-target="#shock-tests"><span class="toc-section-number">25.3</span>  Shock Tests</a>
  <ul class="collapse">
  <li><a href="#brio-wu-shock-tube" id="toc-brio-wu-shock-tube" class="nav-link" data-scroll-target="#brio-wu-shock-tube"><span class="toc-section-number">25.3.1</span>  Brio-Wu shock tube</a></li>
  <li><a href="#ryu-and-jones-test-2a" id="toc-ryu-and-jones-test-2a" class="nav-link" data-scroll-target="#ryu-and-jones-test-2a"><span class="toc-section-number">25.3.2</span>  Ryu and Jones Test 2A</a></li>
  <li><a href="#spherical-blast-waves" id="toc-spherical-blast-waves" class="nav-link" data-scroll-target="#spherical-blast-waves"><span class="toc-section-number">25.3.3</span>  Spherical blast waves</a></li>
  </ul></li>
  <li><a href="#instability-tests" id="toc-instability-tests" class="nav-link" data-scroll-target="#instability-tests"><span class="toc-section-number">25.4</span>  Instability Tests</a>
  <ul class="collapse">
  <li><a href="#kelvin-helmholtz-instability" id="toc-kelvin-helmholtz-instability" class="nav-link" data-scroll-target="#kelvin-helmholtz-instability"><span class="toc-section-number">25.4.1</span>  Kelvin-Helmholtz instability</a></li>
  <li><a href="#rayleigh-taylor-instability" id="toc-rayleigh-taylor-instability" class="nav-link" data-scroll-target="#rayleigh-taylor-instability"><span class="toc-section-number">25.4.2</span>  Rayleigh-Taylor instability</a></li>
  </ul></li>
  <li><a href="#turbulence-tests" id="toc-turbulence-tests" class="nav-link" data-scroll-target="#turbulence-tests"><span class="toc-section-number">25.5</span>  Turbulence Tests</a>
  <ul class="collapse">
  <li><a href="#orszag-tang-vortex" id="toc-orszag-tang-vortex" class="nav-link" data-scroll-target="#orszag-tang-vortex"><span class="toc-section-number">25.5.1</span>  Orszag-Tang vortex</a></li>
  </ul></li>
  <li><a href="#reconnection-tests" id="toc-reconnection-tests" class="nav-link" data-scroll-target="#reconnection-tests"><span class="toc-section-number">25.6</span>  Reconnection Tests</a>
  <ul class="collapse">
  <li><a href="#gem-challenge" id="toc-gem-challenge" class="nav-link" data-scroll-target="#gem-challenge"><span class="toc-section-number">25.6.1</span>  GEM challenge</a></li>
  <li><a href="#current-sheet" id="toc-current-sheet" class="nav-link" data-scroll-target="#current-sheet"><span class="toc-section-number">25.6.2</span>  Current sheet</a></li>
  </ul></li>
  <li><a href="#divergence-free-field-test" id="toc-divergence-free-field-test" class="nav-link" data-scroll-target="#divergence-free-field-test"><span class="toc-section-number">25.7</span>  Divergence-free Field test</a>
  <ul class="collapse">
  <li><a href="#magnetic-field-loop" id="toc-magnetic-field-loop" class="nav-link" data-scroll-target="#magnetic-field-loop"><span class="toc-section-number">25.7.1</span>  Magnetic field loop</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/henry2004y/KeyNotes/edit/master/contents/test.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-test" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Tests</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Verifying the validity of models is critical in performing consistent research. This chapter goes through the numerical tests we can do in plasma physics, and is heavily influenced by the <a href="https://www.astro.princeton.edu/~jstone/Athena/tests/">tests in the Athena MHD code</a>.</p>
<section id="unit-conversion" class="level3" data-number="25.0.1">
<h3 data-number="25.0.1" class="anchored" data-anchor-id="unit-conversion"><span class="header-section-number">25.0.1</span> Unit Conversion</h3>
<p>Most test parameters are listed in dimensionless units. If SI units are required, we need unit conversions. Typically, we need to start with a reference number density, e.g.&nbsp;<span class="math inline">\(n_{ref} = 10\,\mathrm{amu/cc}\)</span>, and magnetic field, e.g.&nbsp;<span class="math inline">\(B_{ref} = 10\,\mathrm{nT}\)</span>. All the rest conversion factors can be derived from these together with other physical constants.</p>
<p>The reference frequency in rad/s is</p>
<p><span class="math display">\[
\omega_{\mathrm{ref}} = \sqrt{\frac{n_\mathrm{ref}e^2}{\epsilon_0 m}}
\]</span></p>
<p>and then the reference length scale in m, which is equivalent to the inertial length, is</p>
<p><span class="math display">\[
l_\mathrm{ref} = d = \frac{c}{\omega_{\mathrm{ref}}} = \sqrt{\frac{m}{\mu_0 e^2 n_\mathrm{ref}}}
\]</span></p>
<p>The time scale in s is the inverse of reference gyrofrequency,</p>
<p><span class="math display">\[
t_\mathrm{ref} = \frac{1}{\Omega_i} = \frac{m_i}{q_i B_\mathrm{ref}}
\]</span></p>
<p>Actually there is a <span class="math inline">\(2\pi\)</span> factor missing here, since we need to convert from gyrofrequency to frequency and then take the inverse for the period. However, <em>traditionally no one did that</em>.</p>
<p>The velocity scale in m/s is the Alfvén speed</p>
<p><span class="math display">\[
u_\mathrm{ref} = \frac{l_\mathrm{ref}}{t_\mathrm{ref}} = \frac{B_\mathrm{ref}}{\sqrt{\mu_0 m_i n_\mathrm{ref}}}
\]</span></p>
<p>The pressure scale can be equivalently derived from the magnetic pressure or dynamic pressure</p>
<p><span class="math display">\[
P_\mathrm{ref} = \frac{B_\mathrm{ref}^2}{2\mu_0} = \frac{1}{2}\rho_\mathrm{ref}u_\mathrm{ref}^2
\]</span></p>
<p>The temperature scale is then</p>
<p><span class="math display">\[
T_\mathrm{ref} = \frac{p_\mathrm{ref}}{n_\mathrm{ref} k_B} = \frac{B_\mathrm{ref}^2}{2\mu_0 k_B n_\mathrm{ref}}
\]</span></p>
<p>In many normalized units, the factor <span class="math inline">\(1/\sqrt{\mu_0}\)</span> is absorbed into the magnetic field, <span class="math display">\[
B^\prime = \frac{B}{\sqrt{\mu_0}}
\]</span></p>
<p>If CGS units is used, then this shall be (???) <span class="math display">\[
B^\prime = \frac{B}{\sqrt{4\pi}}
\]</span></p>
<p>Inserting the initially chosen values, we get a full set of conversion factors from variables in normalized units <span class="math inline">\(n^\prime, B^\prime, u^\prime, p^\prime, T^\prime, \mathcal{E}^\prime\)</span> to SI units <span class="math inline">\(n, B, u, p, T, \mathcal{E}\)</span>:</p>
<p><span class="math display">\[
U_\mathrm{SI} = U^\prime * U_\mathrm{ref}
\]</span></p>
<p>where each conversion factor is summarized in <a href="#tbl-unit-conversion">Table&nbsp;<span>25.1</span></a>.</p>
<div id="tbl-unit-conversion" class="anchored">
<table class="table">
<caption>Table&nbsp;25.1: Unit conversion factors.</caption>
<thead>
<tr class="header">
<th>Variable</th>
<th>Conversion factor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\rho\)</span></td>
<td><span class="math inline">\(n_\mathrm{ref}*m\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(B\)</span></td>
<td><span class="math inline">\(B_\mathrm{ref}\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\rho u\)</span></td>
<td><span class="math inline">\(\frac{B_\mathrm{ref}}{\sqrt{\mu_0 m n_\mathrm{ref}}}\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(p\)</span></td>
<td><span class="math inline">\(\frac{B_\mathrm{ref}^2}{2\mu_0}\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(T\)</span></td>
<td><span class="math inline">\(\frac{B_\mathrm{ref}^2}{2\mu_0 k_B n_\mathrm{ref}}\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mathcal{E}\)</span></td>
<td><span class="math inline">\(\frac{B_\mathrm{ref}^2}{2\mu_0}\)</span></td>
</tr>
</tbody>
</table>
</div>
<section id="example-dimensionless-to-nut" class="level4" data-number="25.0.1.1">
<h4 data-number="25.0.1.1" class="anchored" data-anchor-id="example-dimensionless-to-nut"><span class="header-section-number">25.0.1.1</span> Example: dimensionless to <span class="math inline">\(n,u,T\)</span></h4>
<p>When dealing with velocity distribution functions, one easy way is to write <span class="math inline">\(f(\mathbf{v})=f(\mathbf{v}; n,\mathbf{u},T)\)</span>. For instance, a 3D Maxwellian is given as</p>
<p><span class="math display">\[
f(\mathbf{v}) = n\left( \frac{m}{2\pi k_B T} \right)^{3/2} \exp\left(-\frac{m(\mathbf{v}-\mathbf{u})^2}{2k_B T}\right)
\]</span></p>
<p>From conservative variables <span class="math inline">\((\rho,\rho\mathbf{u},\mathcal{E},\mathbf{B})\)</span> to <span class="math inline">\((n,\mathbf{u},T,\mathbf{B})\)</span>, we have</p>
<p><span class="math display">\[
\begin{aligned}
n_\mathrm{SI} &amp;= \frac{n_\mathrm{ref}}{m}\rho^\prime \\
u_\mathrm{SI} &amp;= u_\mathrm{ref}\left( \frac{\rho^\prime u^\prime}{\rho^\prime} \right) \\
T_\mathrm{SI} &amp;= \frac{(\gamma-1)B_\mathrm{ref}^2}{2\mu_0 k_B n_\mathrm{ref}}\left[ \frac{\mathcal{E}^\prime - {\rho^\prime}^2 - {B^\prime}^2}{n^\prime} \right] \\
B_\mathrm{SI} &amp;= B_\mathrm{ref}B^\prime \\
\end{aligned}
\]</span></p>
</section>
</section>
<section id="errors" class="level2" data-number="25.1">
<h2 data-number="25.1" class="anchored" data-anchor-id="errors"><span class="header-section-number">25.1</span> Errors</h2>
<ol type="1">
<li>Diffusion error: the rate at which the amplitude of the wave decreases.</li>
<li>Dispersion error: the difference between the speed at which the wave propagates in the numerical versus the analytic solution.</li>
</ol>
<p>The error norm usually contains contributions from both. However, one could plot the error as a function of position or phase to track each individually.</p>
</section>
<section id="wave-tests" class="level2" data-number="25.2">
<h2 data-number="25.2" class="anchored" data-anchor-id="wave-tests"><span class="header-section-number">25.2</span> Wave Tests</h2>
<section id="linear-wave" class="level3" data-number="25.2.1">
<h3 data-number="25.2.1" class="anchored" data-anchor-id="linear-wave"><span class="header-section-number">25.2.1</span> Linear wave</h3>
<p>The density, velocity, magnetic field, and total energy are all set to constant values initially. These values can be chosen so that the wave speeds are all well separated, and so that (in MHD) the wavevector is at an arbitrary angle to <span class="math inline">\(\mathbf{B}\)</span>. The precise values chosen for the tests described here are given in the appropriate results section below.</p>
<p>The wave is added to as a perturbation to these constant values of the form <span class="math inline">\(\delta \mathbf{U} = A \mathbf{R} \sin(2\pi x)\)</span>. Here <span class="math inline">\(\mathbf{U}\)</span> is the vector of conserved variables, <span class="math inline">\(A\)</span> is an amplitude, and <span class="math inline">\(\mathbf{R}\)</span> is the right-eigenvector corresponding to the desired wave family. The components of <span class="math inline">\(\mathbf{R}\)</span> for each test are listed in the appropriate results section below. For all the tests shown here, <span class="math inline">\(A = 10^{-6}\)</span>.</p>
<p>The length of the computational domain is set to be one wavelength. Periodic boundary conditions are used. After the wave has propagated one wavelength, we measure the error in the numerical solution by computing the norm of the vector resulting from summing the absolute value of errors in each variable over the grid,</p>
<p><span class="math display">\[
\begin{aligned}
\epsilon &amp;= || \Delta U || = \sqrt{\sum_k (\Delta U_k)^2} \\
&amp;= \sqrt{\sum_k (\sum_{i=1}^{N_x} |U_{k,i}^n - U_{k,i}^0| / N_x)^2}
\end{aligned}
\]</span></p>
<p>Here, <span class="math inline">\(U_{k,i}\)</span> is the numerical solution for the k-th component of the vector of conserved quantities at grid point <span class="math inline">\(i\)</span> and time level <span class="math inline">\(n\)</span>, <span class="math inline">\(U_{k,i}^0\)</span> is the initial numerical solution, and <span class="math inline">\(N_x\)</span> is the number of grid points. Note the initial solution <span class="math inline">\(U_{k,i}^0\)</span> is just the analytic solution which has been discretized to the grid. Since the discretization of the initial condition also introduces error, to measure the error in the integration algorithm it is important to compute errors relative to the initial condition <span class="math inline">\(U_{k,i}^0\)</span> rather than the analytic solution. In 2D (3D), summation over <span class="math inline">\(j (k)\)</span> is required as well.</p>
<p>To compare to the results given here, it is important to</p>
<ol type="1">
<li>Use the same amplitude for the wave</li>
<li>Compute the errors in exactly the same way</li>
<li>Compute the errors at exactly the same time</li>
</ol>
<p>This is an excellent quantitative test of the accuracy and convergence rate of a numerical algorithm. The only drawback is that it involves only linear amplitude oscillations. Thus, this test is not characteristic of the kind of problem codes are written to solve in the first place (after all, the dynamics of linear waves can be treated analytically). A code which does well on this test may still be very poor at shock-capturing. Still, it is nice to know an algorithm reduces to the correct answer in the linear regime. Moreover, since virtually all schemes are first-order for discontinuities such as shocks, smooth problems like this are the only way to measure the actual convergence rate of higher-order schemes.</p>
<p>This test has proved very useful at detecting coding bugs:</p>
<ul>
<li>The errors for left- and right-going waves of the same family should be identical.</li>
<li>If the errors do not converge, something is wrong somewhere.</li>
<li>It is necessary to use double precision and very small wave amplitudes to eliminate round-off error and nonlinear effects.</li>
</ul>
<section id="d-adiabatic-hydrodynamics" class="level4" data-number="25.2.1.1">
<h4 data-number="25.2.1.1" class="anchored" data-anchor-id="d-adiabatic-hydrodynamics"><span class="header-section-number">25.2.1.1</span> 1D Adiabatic Hydrodynamics</h4>
<p>Given <a href="fluid.html#eq-ideal-mhd">Equation&nbsp;<span>5.12</span></a> (with <span class="math inline">\(\mathbf{B}=0\)</span>), <span class="math display">\[
\begin{aligned}
\rho &amp;= 1 \\
\mathbf{u} &amp;= \mathbf{0} \\
p &amp;= 1/\gamma
\end{aligned}
\]</span></p>
<p>with <span class="math inline">\(\gamma = 5/3\)</span>. The conservative variables are <span class="math display">\[
\mathbf{U}=[\rho, \rho u_x, \rho u_y, \rho u_z, E]
\]</span></p>
<p>and the right-eigenvector for a left-going wave is <span class="math display">\[
\mathbf{R}=[1.0, -1.0, 1.0, 1.0, 1.5]
\]</span></p>
<p>When switching from <span class="math inline">\(\mathcal{E}\)</span> to <span class="math inline">\(p\)</span>, we can see from the background and <span class="math inline">\(\mathbf{R}\)</span> that</p>
<p><span class="math display">\[
\delta p = (\gamma-1)\left( \delta\mathcal{E} - \frac{1}{2}\rho \delta u^2 \right) = 0
\]</span></p>
<p>The parameters are summarized in <a href="#tbl-linear-wave-1d-hd">Table&nbsp;<span>25.2</span></a>.</p>
<div id="tbl-linear-wave-1d-hd" class="anchored">
<table class="table">
<caption>Table&nbsp;25.2: 1D adiabatic hydrodynamic linear wave parameters</caption>
<thead>
<tr class="header">
<th>Variable</th>
<th>Background</th>
<th>Perturbation <span class="math inline">\(\mathbf{R}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\rho\)</span></td>
<td>1</td>
<td>1.0</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\rho u_x\)</span></td>
<td>0</td>
<td>-1.0</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\rho u_y\)</span></td>
<td>0</td>
<td>1.0</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\rho u_z\)</span></td>
<td>0</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(p\)</span></td>
<td><span class="math inline">\(\frac{1}{\gamma}\)</span></td>
<td>0.0</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mathcal{E}\)</span></td>
<td><span class="math inline">\(\frac{1}{\gamma(\gamma-1)}\)</span></td>
<td>1.5</td>
</tr>
</tbody>
</table>
</div>
<p>The absolute error in propagating a sound wave to the left one wavelength as a function of the number of grid points <span class="math inline">\(N_x\)</span></p>
</section>
<section id="d-adiabatic-mhd" class="level4" data-number="25.2.1.2">
<h4 data-number="25.2.1.2" class="anchored" data-anchor-id="d-adiabatic-mhd"><span class="header-section-number">25.2.1.2</span> 1D Adiabatic MHD</h4>
<p>Given <a href="fluid.html#eq-ideal-mhd">Equation&nbsp;<span>5.12</span></a>,</p>
<p><span class="math display">\[
\begin{aligned}
\rho &amp;= 1 \\
\mathbf{u} &amp;= \mathbf{0} \\
p &amp;= 1/\gamma \\
\mathbf{B} &amp;= [1, \sqrt{2}, 0.5]*(4\pi)^{1/2} \\
\end{aligned}
\]</span></p>
<p>with <span class="math inline">\(\gamma = 5/3\)</span>. Thus, the fast magnetosonic speed is 2.0, the Alfvén speed is 1.0, and the slow magnetosonic speed is 0.5.</p>
<p><span class="math display">\[
\mathbf{U} = [\rho, \rho u_x, \rho u_y, \rho u_z, E, B_y, B_z]
\]</span></p>
<p>then the right eigenvectors for left going waves are as follows:</p>
<ul>
<li>For a fast magnetosonic wave:</li>
</ul>
<pre class="{julia}"><code>U = [
4.472135954999580e-01
-8.944271909999160e-01
4.216370213557840e-01
1.490711984999860e-01
2.012457825664615e+00
8.432740427115680e-01
2.981423969999720e-01 ]</code></pre>
<ul>
<li>For a Alfvén wave:</li>
</ul>
<pre class="{julia}"><code>U = [
0.0
0.0
-3.333333333333333e-01
9.428090415820634e-01
0.0
-3.333333333333333e-01
9.428090415820634e-01 ]</code></pre>
<ul>
<li>For a slow magnetosonic wave:</li>
</ul>
<pre class="{julia}"><code>U = [
8.944271909999159e-01
-4.472135954999579e-01
-8.432740427115680e-01
-2.981423969999720e-01
6.708136850795449e-01
-4.216370213557841e-01
-1.490711984999860e-01 ]</code></pre>
<p>The parameters are summarized in <a href="#tbl-linear-wave-1d-mhd">Table&nbsp;<span>25.3</span></a>.</p>
<div id="tbl-linear-wave-1d-mhd" class="tbl-parent quarto-layout-panel anchored">
<div class="panel-caption table-caption">
<p>Table&nbsp;25.3: 1D adiabatic MHD linear wave parameters</p>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div id="tbl-linear-wave-1d-mhd-1" class="quarto-layout-cell quarto-layout-cell-subref anchored" data-ref-parent="tbl-linear-wave-1d-mhd" style="flex-basis: 100.0%;justify-content: center;">
<table class="table">
<caption>(a) fast magnetosonic wave</caption>
<colgroup>
<col style="width: 30%">
<col style="width: 35%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Background</th>
<th style="text-align: left;">Perturbation <span class="math inline">\(\mathbf{R}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\rho\)</span></td>
<td style="text-align: left;">1.0</td>
<td style="text-align: left;">4.472135954999580e-1</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\rho u_x\)</span></td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">-8.944271909999160e-1</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\rho u_y\)</span></td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">4.216370213557840e-1</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\rho u_z\)</span></td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">1.490711984999860e-1</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\mathcal{E}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\frac{1}{\gamma(\gamma-1)}+\frac{13}{8}\)</span></td>
<td style="text-align: left;">2.012457825664615</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(B_x / \sqrt{4\pi}\)</span></td>
<td style="text-align: left;">1.0</td>
<td style="text-align: left;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(B_y / \sqrt{4\pi}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\sqrt{2}\)</span></td>
<td style="text-align: left;">8.432740427115680e-1</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(B_z / \sqrt{4\pi}\)</span></td>
<td style="text-align: left;">0.5</td>
<td style="text-align: left;">2.981423969999720e-1</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div id="tbl-linear-wave-1d-mhd-2" class="quarto-layout-cell quarto-layout-cell-subref anchored" data-ref-parent="tbl-linear-wave-1d-mhd" style="flex-basis: 100.0%;justify-content: center;">
<table class="table">
<caption>(b) Alfvén wave</caption>
<colgroup>
<col style="width: 30%">
<col style="width: 35%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Background</th>
<th style="text-align: left;">Perturbation <span class="math inline">\(\mathbf{R}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\rho\)</span></td>
<td style="text-align: left;">1.0</td>
<td style="text-align: left;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\rho u_x\)</span></td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\rho u_y\)</span></td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">-3.333333333333333e-1</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\rho u_z\)</span></td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">9.428090415820634e-1</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\mathcal{E}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\frac{1}{\gamma(\gamma-1)}\)</span></td>
<td style="text-align: left;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(B_x / \sqrt{4\pi}\)</span></td>
<td style="text-align: left;">1.0</td>
<td style="text-align: left;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(B_y / \sqrt{4\pi}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\sqrt{2}\)</span></td>
<td style="text-align: left;">-3.333333333333333e-1</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(B_z / \sqrt{4\pi}\)</span></td>
<td style="text-align: left;">0.5</td>
<td style="text-align: left;">9.428090415820634e-1</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div id="tbl-linear-wave-1d-mhd-3" class="quarto-layout-cell quarto-layout-cell-subref anchored" data-ref-parent="tbl-linear-wave-1d-mhd" style="flex-basis: 100.0%;justify-content: center;">
<table class="table">
<caption>(c) slow magnetosonic wave</caption>
<colgroup>
<col style="width: 30%">
<col style="width: 35%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Background</th>
<th style="text-align: left;">Perturbation <span class="math inline">\(\mathbf{R}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\rho\)</span></td>
<td style="text-align: left;">1.0</td>
<td style="text-align: left;">8.944271909999159e-1</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\rho u_x\)</span></td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">-4.472135954999579e-1</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\rho u_y\)</span></td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">-8.432740427115680e-1</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\rho u_z\)</span></td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">-2.981423969999720e-1</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\mathcal{E}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\frac{1}{\gamma(\gamma-1)}\)</span></td>
<td style="text-align: left;">6.708136850795449e-1</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(B_x / \sqrt{4\pi}\)</span></td>
<td style="text-align: left;">1.0</td>
<td style="text-align: left;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(B_y / \sqrt{4\pi}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\sqrt{2}\)</span></td>
<td style="text-align: left;">-4.216370213557841e-1</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(B_z / \sqrt{4\pi}\)</span></td>
<td style="text-align: left;">0.5</td>
<td style="text-align: left;">-1.490711984999860e-1</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>In some cases, we need to convert from conservative variables to other set of variables, e.g.&nbsp;<span class="math inline">\((n,\mathbf{u},p,\mathbf{B})\)</span>. The number density perturbation is <span id="eq-number-mass-density-conversion"><span class="math display">\[
\delta n = \frac{\delta \rho}{m} = \frac{\rho_0}{m}\sin 2\pi x
\tag{25.1}\]</span></span> Assuming background <span class="math inline">\(u_0=0\)</span>, <span id="eq-velocity-momentumflux-conversion"><span class="math display">\[
\delta u = \frac{1}{\rho}\left[ \delta(\rho u) - (\delta \rho) u \right] = \frac{1}{\rho_0}\delta(\rho u)
\tag{25.2}\]</span></span> Given the perturbation of energy density <span class="math display">\[
\begin{aligned}
\mathcal{E} &amp;= \frac{p}{\gamma-1} + \frac{\rho u^2}{2} + \frac{B^2}{2\mu_0} \\
\delta\mathcal{E} &amp;= \frac{\delta p}{\gamma-1} + \frac{\rho_0\delta u^2}{2} + \frac{1}{2\mu_0}\left( 2B_0\delta B + \delta B^2 \right)
\end{aligned}
\]</span></p>
<p>the pressure perturbation is then</p>
<p><span id="eq-pressure-energyflux-conversion"><span class="math display">\[
\begin{aligned}
\delta p &amp;= (\gamma-1)\left[ \delta\mathcal{E} - \frac{1}{2}\rho\delta u^2 - \frac{1}{2\mu_0}\left( 2B_0\delta B + \delta B^2 \right) \right] \\
&amp;= (\gamma-1)\left[ \delta\mathcal{E} - \frac{1}{2\rho_0}\delta(\rho u)^2 - \frac{1}{2\mu_0}\left( 2B_0\delta B + \delta B^2 \right) \right]
\end{aligned}
\tag{25.3}\]</span></span></p>
<p>If the input is <span class="math inline">\(T\)</span> instead of <span class="math inline">\(p\)</span>, we have <span id="eq-temperature-pressure-conversion"><span class="math display">\[
\begin{aligned}
\delta T &amp;= \frac{1}{k_B\, n}\left[ \delta p - \delta n\, k_B\, T \right] = \frac{m}{k_B\, \rho}\left[ \delta p - \delta \rho\frac{k_B\, T}{m} \right] \\
&amp;= \frac{m}{k_B\,\rho_0}\delta p - \frac{\delta\rho}{\rho_0}T
\end{aligned}
\tag{25.4}\]</span></span></p>
</section>
<section id="d-adiabatic-mhd-1" class="level4" data-number="25.2.1.3">
<h4 data-number="25.2.1.3" class="anchored" data-anchor-id="d-adiabatic-mhd-1"><span class="header-section-number">25.2.1.3</span> 2D Adiabatic MHD</h4>
<p>In this case, we use the same values as for the 1D adiabatic MHD test, but we use a 2D grid of size <span class="math inline">\(0 \le x \le 2\)</span> and <span class="math inline">\(0 \le y \le 1\)</span>. We use twice as many grid points in the x-direction at every resolution (e.g.&nbsp;our highest resolution is <span class="math inline">\(512 \times 256\)</span>), thus the grid is rectangular, but each cell is square. The wave propagates along the diagonal of the grid, at an angle <span class="math inline">\(\theta = \tan^{-1}(0.5) \approx 26.6\)</span> degrees with respect to the x-axis. Since the wave does not propagate along the diagonals of the grid cells, we guarantee the x- and y-fluxes are different; that is the problem is truly multi-dimensional.</p>
</section>
</section>
<section id="d-adiabatic-mhd-2" class="level3" data-number="25.2.2">
<h3 data-number="25.2.2" class="anchored" data-anchor-id="d-adiabatic-mhd-2"><span class="header-section-number">25.2.2</span> 3D Adiabatic MHD</h3>
<p>Now we use a 3D grid of size <span class="math inline">\(0 \le x \le 3\)</span> and <span class="math inline">\(0 \le y \le 1.5\)</span>, and <span class="math inline">\(0 \le z \le 1.5\)</span>. The grid is of size <span class="math inline">\(2N\times N \times N\)</span>. The wave propogates along the grid diagonal, again guaranteeing a truly multidimensional test. The background state is identical to the 1D test values.</p>
</section>
<section id="circularly-polarized-alfvén-wave" class="level3" data-number="25.2.3">
<h3 data-number="25.2.3" class="anchored" data-anchor-id="circularly-polarized-alfvén-wave"><span class="header-section-number">25.2.3</span> Circularly polarized Alfvén wave</h3>
<p><span class="math display">\[
\begin{aligned}
\rho &amp;= 1.0 \\
p &amp;= 0.1 \\
v_\perp &amp;= 0.1\sin(2\pi x_\parallel) \\
v_z &amp;= 0.1\cos(2\pi x_\parallel) \\
B_\perp &amp;= 0.1\sin(2\pi x_\parallel) \\
B_z &amp;= 0.1\cos(2\pi x_\parallel)
\end{aligned}
\]</span></p>
<p>with <span class="math inline">\(\gamma = 5/3\)</span> and <span class="math inline">\(x\parallel = (x \cos\alpha + y\sin\alpha)\)</span> where <span class="math inline">\(\alpha\)</span> is the angle at which the wave propagates with respect to the grid. Here <span class="math inline">\(v_\perp\)</span> and <span class="math inline">\(B_\perp\)</span> are the components of velocity and magnetic field perpendicular to the wavevector. They are related to the components stored on the grid <span class="math inline">\(B_x\)</span> and <span class="math inline">\(B_y\)</span> via</p>
<p><span class="math display">\[
\begin{aligned}
B_\perp = B_y\cos\alpha - B_x\sin\alpha \\
B_\parallel = B_x\cos\alpha + B_y\sin\alpha
\end{aligned}
\]</span></p>
<p>For 2D the computational domain is of size <span class="math inline">\(L_x = 2L_y\)</span>, with <span class="math inline">\(N_x = 2N_y\)</span>. Thus, the grid is rectangular, but each cell is square. The wave propagates along the diagonal of the grid, at an angle <span class="math inline">\(\theta = \tan^{-1}(0.5) \approx 26.6\)</span> degrees with respect to the x-axis. Since the wave does not propagate along the diagonals of the grid cells, we guarantee the x- and y-fluxes are different; that is the problem is truly multi-dimensional.</p>
<p>The wave is an exact nonlinear solution to the MHD equations, allowing one to test the algorithm in the nonlinear regime. Although nonlinear amplitude Alfvén waves are subject to a parametric instability which causes them to decay into magnetosonic waves, the instability should not be present for the parameters defined here. Since the problem is smooth, it can be used for convergence testing. Running the test with smaller pressure (higher β) and/or larger amplitudes is a good test of how robust is the algorithm.</p>
<p>See more in <a href="https://www.astro.princeton.edu/~jstone/Athena/tests/cp-alfven-wave/cp-alfven.html">reference</a> and <span class="citation" data-cites="toth2000b">(<a href="#ref-toth2000b" role="doc-biblioref">Tóth 2000</a>)</span>.</p>
</section>
<section id="light-wave" class="level3" data-number="25.2.4">
<h3 data-number="25.2.4" class="anchored" data-anchor-id="light-wave"><span class="header-section-number">25.2.4</span> Light wave</h3>
</section>
<section id="firehose-instability" class="level3" data-number="25.2.5">
<h3 data-number="25.2.5" class="anchored" data-anchor-id="firehose-instability"><span class="header-section-number">25.2.5</span> Firehose instability</h3>
</section>
<section id="mirror-mode-instability" class="level3" data-number="25.2.6">
<h3 data-number="25.2.6" class="anchored" data-anchor-id="mirror-mode-instability"><span class="header-section-number">25.2.6</span> Mirror mode instability</h3>
</section>
</section>
<section id="shock-tests" class="level2" data-number="25.3">
<h2 data-number="25.3" class="anchored" data-anchor-id="shock-tests"><span class="header-section-number">25.3</span> Shock Tests</h2>
<section id="brio-wu-shock-tube" class="level3" data-number="25.3.1">
<h3 data-number="25.3.1" class="anchored" data-anchor-id="brio-wu-shock-tube"><span class="header-section-number">25.3.1</span> Brio-Wu shock tube</h3>
<p>This test is an MHD shocktube, where the right and left states are initalized to different values. The initial left/right values are</p>
<p><span class="math display">\[
\begin{aligned}
\rho &amp;= 1.0,\, 0.125 \\
u_x &amp;= 0.0,\, 0.0 \\
u_y &amp;= 0.0,\, 0.0 \\
u_z &amp;= 1.0,\, -1.0 \\
B_x &amp;= 0.75,\, 0.75 \\
B_y &amp;= 0.0,\, 0.0 \\
B_z &amp;= 0.0,\, 0.0 \\
p &amp;= 1.0,\, 0.1
\end{aligned}
\]</span></p>
<p>and <span class="math inline">\(\gamma = 2\)</span>. The hydrodynamic portion of the initial conditions are the same as for the Sod shock tube problem.</p>
<p>This is a standard test for MHD codes for checking whether the code can accurately represent the shocks, rarefactions, contact discontinuities, and the compound structures of MHD.</p>
</section>
<section id="ryu-and-jones-test-2a" class="level3" data-number="25.3.2">
<h3 data-number="25.3.2" class="anchored" data-anchor-id="ryu-and-jones-test-2a"><span class="header-section-number">25.3.2</span> Ryu and Jones Test 2A</h3>
<p>This test is an MHD shocktube, where the right and left states are initialized to different values. It involves a three-dimensional field and velocity structure and rotation of the plane of the magnetic field. The initial left/right values are</p>
<p><span class="math display">\[
\begin{aligned}
\rho &amp;= 1.08,\, 1.0 \\
u_x &amp;= 1.2,\, 0.0 \\
u_y &amp;= 0.01,\, 0.0 \\
u_z &amp;= 0.5,\, 0.0 \\
B_x &amp;= 3.6/\sqrt{4\pi},\, 2.0/\sqrt{4\pi} \\
B_y &amp;= 2.0/\sqrt{4\pi},\, 4.0/\sqrt{4\pi} \\
B_z &amp;= 2.0/\sqrt{4\pi},\, 2.0/\sqrt{4\pi} \\
p &amp;= 0.95,\, 1.0
\end{aligned}
\]</span></p>
<p>This test contains fast shocks, slow shocks, and rotational discontinuities which propagate to each side of the contact discontinuity. The ability of the scheme to capture all 7 waves in MHD can be checked with this single test.</p>
</section>
<section id="spherical-blast-waves" class="level3" data-number="25.3.3">
<h3 data-number="25.3.3" class="anchored" data-anchor-id="spherical-blast-waves"><span class="header-section-number">25.3.3</span> Spherical blast waves</h3>
<p>We used a rectangular domain, <span class="math inline">\(-0.5 \le x \le 0.5; -0.75 \le y \le 0.75\)</span>. The boundary conditions are periodic everywhere. This non-square domain and periodic boundary conditions produces complex shock-shock and shock-CD interactions at late times.</p>
<p>The initial conditions are</p>
<p><span class="math display">\[
\begin{aligned}
\rho &amp;= 1.0 \\
\mathbf{u} &amp;= [0.0, 0.0, 0.0] \\
p &amp;= 0.1
\end{aligned}
\]</span></p>
<p>with <span class="math inline">\(\gamma = 5/3\)</span>. Initial velocities are zero everywhere. Within the region <span class="math inline">\(r &lt; 0.1\)</span>, <span class="math inline">\(p = 10.0\)</span> (that is, 100 times the ambient pressure). For the MHD problem, the initial magnetic field is uniform everywhere with <span class="math inline">\(B_x / \sqrt{4\pi} = B_y / \sqrt{4\pi} = 1/\sqrt{2}\)</span>.</p>
<p>Although this test is not very quantitative, it makes great movies!</p>
<p>At early times, it is important that the out-going blast wave is spherical and shows no grid alignment effects. At late times, the interaction of the blast wave with the CD at the edge of the evacuated bubble in the center produces filaments of dense gas by the Richtmyer-Meshkov instability. It is important these fingers are sharp and not diffused away. Moreover, for the hydrodynamical problem, the pattern of the fingers should be exactly symmetric top-to-bottom and left-to-right. For the MHD problem, the Richtmyer-Meshkov instability is suppressed, and no fingers are evident.</p>
</section>
</section>
<section id="instability-tests" class="level2" data-number="25.4">
<h2 data-number="25.4" class="anchored" data-anchor-id="instability-tests"><span class="header-section-number">25.4</span> Instability Tests</h2>
<section id="kelvin-helmholtz-instability" class="level3" data-number="25.4.1">
<h3 data-number="25.4.1" class="anchored" data-anchor-id="kelvin-helmholtz-instability"><span class="header-section-number">25.4.1</span> Kelvin-Helmholtz instability</h3>
<p>We use a square domain, <span class="math inline">\(-0.5 \le x \le 0.5; -0.5 \le y \le 0.5\)</span>. The boundary conditions are periodic everywhere. For <span class="math inline">\(|y| &gt; 0.25\)</span>, we set <span class="math inline">\(\rho = 1\)</span> and <span class="math inline">\(u_x = -0.5\)</span>, for <span class="math inline">\(|y| \le 0.25\)</span>, <span class="math inline">\(\rho = 2\)</span> and <span class="math inline">\(u_x = 0.5\)</span>. The pressure is 2.5 everywhere, and <span class="math inline">\(\gamma = 1\)</span>.4, giving a Mach number of about 0.377 in the <span class="math inline">\(\rho=2\)</span> gas, and about 0.267 in the <span class="math inline">\(\rho = 1\)</span> gas. The interface between the two oppositely directed streams is a discontinuity, that is a “slip surface”. We use different densities in the two fluids to make visualization of the interface easier.</p>
<p>For the MHD problem, the initial magnetic field is uniform everywhere with <span class="math inline">\(B_x / \sqrt{4\pi} = 0.5\)</span>.</p>
<p>To seed the instability, we add random numbers to both the x- and y-components of the velocity with peak-to-peak amplitude of 0.01.</p>
<p>At early times, one can check that the growth rate of the transverse component of the velocity agrees with the prediction from linear theory. This requires initializing a single-mode perturbation rather than a spectrum of perturbations as we have done here.</p>
<p>At late times, once the instability has gone fully nonlinear, it is difficult to make quantitative comparisons. However, the sharpness of the boundary between the two streams is an indication of the numerical diffusion of the scheme. For example, if the HLLE Riemann solver is used, diffusion at the interface is significant enough to suppress the instability.</p>
</section>
<section id="rayleigh-taylor-instability" class="level3" data-number="25.4.2">
<h3 data-number="25.4.2" class="anchored" data-anchor-id="rayleigh-taylor-instability"><span class="header-section-number">25.4.2</span> Rayleigh-Taylor instability</h3>
<p>For the single-mode test, we use a rectangular domain, <span class="math inline">\(-0.25 \le x \le 0.25; -0.75 \le y \le 0.75\)</span>. The boundary conditions are periodic at <span class="math inline">\(|x| = 0.25\)</span>, and reflecting walls at <span class="math inline">\(|y| = 0.75\)</span>. For <span class="math inline">\(y&gt;0\)</span> the density is 2.0, while for <span class="math inline">\(y \le 0\)</span> it is 1.0. A constant gravitational acceleration <span class="math inline">\(g = 0.1\)</span> must be added to the equations of motion. The pressure is given by the condition of hydrostatic equilibrium, that is <span class="math inline">\(p = p_0 - 0.1\rho y\)</span>, where <span class="math inline">\(p_0=2.5\)</span>, and <span class="math inline">\(\gamma=1.4\)</span>. This gives a sound speed of 3.5 in the low density medium at the interface.</p>
<p>The structures which appear in the nonlinear regime are very sensitive to the nature of the perturbations used to seed the instability. To avoid gridding errors associated with perturbing the interface, we instead perturb the velocities. For the single-mode perturbation, we set <span class="math inline">\(u_y = 0.01[1 + \cos(4\pi x)][1 + \cos(3\pi y)]/4\)</span>.</p>
<p>For the multimode perturbation, we use a domain of size <span class="math inline">\(-0.25 \le x \le 0.25; -0.375 \le y \le 0.375\)</span>, and set <span class="math inline">\(u_y = A[1 + \cos(8\pi y/3)]/2\)</span>, where <span class="math inline">\(A\)</span> is a random number at each zone with a peak-to-peak amplitude of 0.01.</p>
<p>The way in which source terms are included in the algorithm can have a strong effect on the outcome of this test. For example, for Godunov schemes, if the source term is added using operator splitting, grid noise generated by the lack of an exact numerical equilibrium can perturb the interface and seed structure. If the source terms are included directly in the reconstruction and integration steps, it is able to hold hydrostatic equilibrium automatically.</p>
<p>At early times, one can check that the growth rate of the vertical component of the velocity agrees with the prediction from linear theory.</p>
<p>At late times, once the instability has gone fully nonlinear, it is difficult to make quantitative comparisons. However, the sharpness of the boundary between the two fluids is an indication of the numerical diffusion of the scheme. Also, the amount of fine scale struture induced by secondary KH instabilities is sensitive to the way the interface is perturbed, and how sharp the algorithm preserves the contact discontinuity. It is not always clear that sharper is better, however. For example the “contact steepener” in the PPM algorithm can introduce “stair stepping” in contact discontinuities in multidimensions, which in turn can cause KH rolls to be seeded by grid noise.</p>
</section>
</section>
<section id="turbulence-tests" class="level2" data-number="25.5">
<h2 data-number="25.5" class="anchored" data-anchor-id="turbulence-tests"><span class="header-section-number">25.5</span> Turbulence Tests</h2>
<section id="orszag-tang-vortex" class="level3" data-number="25.5.1">
<h3 data-number="25.5.1" class="anchored" data-anchor-id="orszag-tang-vortex"><span class="header-section-number">25.5.1</span> Orszag-Tang vortex</h3>
<p>We use a square domain, <span class="math inline">\(0 \le x \le 1; 0 \le y \le 1\)</span>. The boundary conditions are periodic everywhere. The density <span class="math inline">\(\rho\)</span> is <span class="math inline">\(25/(36\pi)\)</span> and the pressure is <span class="math inline">\(5/(12\pi)\)</span> everywhere, and <span class="math inline">\(\gamma = 5/3\)</span>. Note that this choice gives <span class="math inline">\(u_s^2 = \gamma p/\rho = 1\)</span>. The initial velocities are periodic with <span class="math inline">\(u_x = -\sin(2\pi y)\)</span> and <span class="math inline">\(u_y = \sin(2\pi x)\)</span>. The magnetic field is initialized using a periodic vector potential defined at zone corners; <span class="math inline">\(A_z = B_0 (\cos(4\pi x)/(4\pi) + \cos(2\pi y)/(2\pi))\)</span>, with <span class="math inline">\(B_0 = 1/\sqrt(4\pi)\)</span>. Face-centered magnetic fields are computed using <span class="math inline">\(\mathbf{B} = \nabla\times \mathbf{A}\)</span> to guarantee <span class="math inline">\(\nabla\cdot\mathbf{B}=0\)</span> initially. This gives <span class="math inline">\(B_x = -B_0 \sin(2\pi y)\)</span> and <span class="math inline">\(B_y = B_0 \sin(4\pi x)\)</span>.</p>
<p>The Orszag-Tang vertex is a well-known model problem for testing the transition to supersonic 2D MHD turbulence. Thus, the problem tests how robust the code is at handling the formation of MHD shocks, and shock-shock interactions. The problem can also provide some quanititative estimates of how significant magnetic monopoles affect the numerical solutions, testing the <span class="math inline">\(\nabla\cdot\mathbf{B}=0\)</span> condition. Finally, the problem is a very common test of numerical MHD codes in two dimensions, and has been used in many previous studies. As such, it provides a basis for consistent comparison of codes.</p>
</section>
</section>
<section id="reconnection-tests" class="level2" data-number="25.6">
<h2 data-number="25.6" class="anchored" data-anchor-id="reconnection-tests"><span class="header-section-number">25.6</span> Reconnection Tests</h2>
<section id="gem-challenge" class="level3" data-number="25.6.1">
<h3 data-number="25.6.1" class="anchored" data-anchor-id="gem-challenge"><span class="header-section-number">25.6.1</span> GEM challenge</h3>
<p>This 2D setup is based on <span class="citation" data-cites="birn2001gem">(<a href="#ref-birn2001gem" role="doc-biblioref">Birn et al. 2001</a>)</span>. The computation is carried out in a rectangular domain <span class="math inline">\(-L_x/2 \le x\le L_x/2\)</span> and <span class="math inline">\(-L_z/2\le z \le L_z/2\)</span>. The system is taken to be periodic in the x direction with ideal conducting boundaries at <span class="math inline">\(z=\pm L_z/2\)</span>. Thus the boundary conditions on the magnetic fields at the z boundaries are <span class="math inline">\(B_z=\partial B_x/\partial z = \partial B_y/\partial z = 0\)</span> with corresponding conditions on the electric fields and particle or fluid quantities. Open boundary conditions are used for all quantities.</p>
<p>The equilibrium chosen for the reconnection challenge problem is a Harris equilibrium with a floor in the density outside of the current layer. The magnetic field is given by</p>
<p><span class="math display">\[
B_x(z) = B_0 \tanh(z/\lambda)
\]</span></p>
<p>where <span class="math inline">\(\lambda\)</span> is the current sheet scale size, and the density by</p>
<p><span class="math display">\[
n(z) = n_0 \text{sech}^2(z/\lambda) + n_\infty
\]</span></p>
<p>The electron and ion temperatures, <span class="math inline">\(T_e\)</span> and <span class="math inline">\(T_i\)</span>, are taken to be uniform in the initial state. We assume the plasma <span class="math inline">\(\beta = (p_i+p_e)/p_B=1\)</span> initially.</p>
<p>The normalization of the space and time scales of the system is chosen to be the ion inertial length <span class="math inline">\(d_i=c/\omega_{pi}\)</span> and the ion cyclotron frequency <span class="math inline">\(\Omega_i^{-1}\)</span>, where <span class="math inline">\(\omega_{pi}^2 = n_0e^2/\epsilon_0 m_i\)</span> is evaluated with the density <span class="math inline">\(n_0\)</span> and the ion gyrofrequency <span class="math inline">\(\Omega_i = eB_0/m_i\)</span> is evaluated at the peak magnetic field. The velocities are then normalized to the Alfvén speed <span class="math inline">\(v_A\)</span>. In the normalized units, <span class="math inline">\(B_0 = 1\)</span> and <span class="math inline">\(n_0 = 1\)</span>. Specific parameters for the simulations are <span class="math inline">\(L_x = 25.6, L_z = 12.8, \lambda=0.5, n_\infty/n_0 = 0.2\)</span>, and <span class="math inline">\(T_e/T_i = 0.2\)</span>. <span class="math inline">\(m_i/m_e = 25\)</span> is assumed if required.</p>
<p>The initial magnetic island is specified through the perturbation in the magnetic flux,</p>
<p><span class="math display">\[
\psi(x,z) = \psi_0 \cos(2\pi x/L_x)\cos(\pi z/L_z)
\]</span></p>
<p>where the magnetic perturbation is given by <span class="math inline">\(\mathbf{B} = \hat{y}\times\nabla\psi\)</span>, or more specifically,</p>
<p><span class="math display">\[
\begin{aligned}
B_{1x} &amp;= -\psi_0\Big(\frac{\pi}{L_z}\Big)\cos(2\pi x/L_x)\sin(\pi z/L_z) \\
B_{1z} &amp;= \psi_0\Big(\frac{2\pi}{L_x}\Big)\sin(2\pi x/L_x)\cos(\pi z/L_z)
\end{aligned}
\]</span></p>
<p>In normalized units <span class="math inline">\(\psi_0 = 0.1\)</span>, which produces an initial island width which is comparable to the initial width of the current layer. The rationale for such a large initial perturbation is to put the system in the nonlinear regime of magnetic reconnection from the beginning of the simulation.</p>
<p>The initial setup is shown in <a href="#fig-GEM-currentsheet">Figure&nbsp;<span>25.1</span></a>.</p>
<div id="fig-GEM-currentsheet" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="../images/current_sheet_initial.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;25.1: Initial density and magnetic field in the GEM current sheet setup.</figcaption><p></p>
</figure>
</div>
<section id="why-do-we-need-to-resolve-ion-inertial-length" class="level4" data-number="25.6.1.1">
<h4 data-number="25.6.1.1" class="anchored" data-anchor-id="why-do-we-need-to-resolve-ion-inertial-length"><span class="header-section-number">25.6.1.1</span> Why do we need to resolve ion inertial length</h4>
<p>Physically, electrons and ions separate at the scale of ion inertial length. Numerically, Hall term is important only when cell size is small enough to resolve the ion initial length. The reason is as follows. The Ohm’s law is</p>
<p><span class="math display">\[
\mathbf{E} = -(\mathbf{U}+\mathbf{U}_H)\times\mathbf{H}
\]</span></p>
<p>Assume the typical flow velocity is Alfvén velocity: <span class="math inline">\(\mathbf{U} = \mathbf{V}_A\)</span>. The Hall velocity is estimated as:</p>
<p><span class="math display">\[
\mathbf{U}_H = -\frac{\mathbf{J}}{ne} = -\frac{\nabla\times\mathbf{B}}{\mu_0ne} \sim -\frac{|dB|}{\mu_0ne\Delta x} \sim -\frac{|B|}{\mu_0ne\Delta x}
\]</span></p>
<p>The approximation <span class="math inline">\(dB\approx B\)</span> is valid for relatively coarse grid size; for fine discrete cell sizes, this approximation does not hold, so magnetic field cannot cancel out in the following estimation. Let us now assume we can make this assumption. Then the ratio of Hall velocity and Alfvén velocity is:</p>
<p><span class="math display">\[
\frac{|\mathbf{U}_H|}{|\mathbf{V}_A|} = \frac{c/\omega_{pi}}{\mu_0 \Delta x}
\]</span></p>
<p>Ion inertial length is also important for PIC: if particle’s velocity is assumed to be Alfvén velocity, then ion inertial length is the same as ion gyroradius.</p>
</section>
</section>
<section id="current-sheet" class="level3" data-number="25.6.2">
<h3 data-number="25.6.2" class="anchored" data-anchor-id="current-sheet"><span class="header-section-number">25.6.2</span> Current sheet</h3>
<p>The grid is a square with <span class="math inline">\(-0.5 \le x \le 0.5\)</span> and <span class="math inline">\(-0.5 \le y \le 0.5\)</span>. The density and pressure are uniform everywhere, with <span class="math inline">\(\rho = 1\)</span> and <span class="math inline">\(p = \beta/2\)</span> where <span class="math inline">\(\beta\)</span> is an input parameter. For <span class="math inline">\(|x| &gt; 0.25\)</span> we set <span class="math inline">\(B_y / \sqrt{4π} = 1\)</span>, otherwise <span class="math inline">\(B_y / \sqrt{4π} = -1\)</span>. The velocities are <span class="math inline">\(u_x = A \sin(2\pi y)\)</span> (where <span class="math inline">\(A\)</span> is an amplitude) and <span class="math inline">\(u_y = 0\)</span>. The “standard” test uses <span class="math inline">\(\beta = 0.1\)</span> and <span class="math inline">\(A = 0.1\)</span>, although part of the point of this test is to see how small (large) a value of <span class="math inline">\(\beta (A)\)</span> is required to break the code.</p>
<p>Although we do not know the analytic solution for this problem, it may be an excellent test of the robustness of the algorithm. For ideal MHD, initially the solution should be nonlinearly (???) polarized Alfvén waves propagating along the field in the y-direction (which quickly generate magnetosonic waves since the magnetic pressure does not remain constant). However, because of the two current sheets in the problem (at <span class="math inline">\(x = \pm0.25\)</span>), reconnection inevitably occurs. Because <span class="math inline">\(\beta &lt; 1\)</span>, this reconnection drives strong over-pressurized regions that launch magnetosonic waves transverse to the field. Moreover, as reconnection changes the topology of the field lines, magnetic islands will form, grow, and merge. The point of the test is to make sure the algorithm can follow this evolution for as long as possible without crashing. Keeping <span class="math inline">\(\nabla\cdot\mathbf{B}=0\)</span> as the field toplogy undergoes complex changes could be important.</p>
</section>
</section>
<section id="divergence-free-field-test" class="level2" data-number="25.7">
<h2 data-number="25.7" class="anchored" data-anchor-id="divergence-free-field-test"><span class="header-section-number">25.7</span> Divergence-free Field test</h2>
<section id="magnetic-field-loop" class="level3" data-number="25.7.1">
<h3 data-number="25.7.1" class="anchored" data-anchor-id="magnetic-field-loop"><span class="header-section-number">25.7.1</span> Magnetic field loop</h3>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-birn2001gem" class="csl-entry" role="doc-biblioentry">
Birn, J, JF Drake, MA Shay, BN Rogers, RE Denton, M Hesse, M Kuznetsova, et al. 2001. <span>“Geospace Environmental Modeling (GEM) Magnetic Reconnection Challenge.”</span> <em>Journal of Geophysical Research: Space Physics</em> 106 (A3): 3715–19. <a href="https://doi.org/10.1029/1999JA900449">https://doi.org/10.1029/1999JA900449</a>.
</div>
<div id="ref-toth2000b" class="csl-entry" role="doc-biblioentry">
Tóth, Gábor. 2000. <span>“The∇<span></span> b= 0 Constraint in Shock-Capturing Magnetohydrodynamics Codes.”</span> <em>Journal of Computational Physics</em> 161 (2): 605–52. https://doi.org/<a href="https://doi.org/10.1006/jcph.2000.6519">https://doi.org/10.1006/jcph.2000.6519</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../contents/hybrid.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Hybrid Methods</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../contents/appendix.html" class="pagination-link">
        <span class="nav-page-text">Appendix</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>